namespace MFM.Lbg.Orcs {
    using Microsoft.XLANGs.BaseTypes;
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.BizTalk.Schema.Compiler", "3.0.1.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [SchemaType(SchemaTypeEnum.Document)]
    [System.SerializableAttribute()]
    [SchemaRoots(new string[] {@"COMMODITIESMbo", @"COMMODITIESMboSet", @"COMMODITIESMboKey", @"COMMODITIESMboKeySet", @"COMMODITIESMboQuery", @"MTFMCOMMODITY_QUERY", @"MTFMCOMMODITY_QUERYSet", @"MTFMCOMMODITY_QUERYQuery", @"UpdateMTFMCOMMODITY_QUERY", @"QueryMTFMCOMMODITY_QUERY", @"CreateMTFMCOMMODITY_QUERY", @"SyncMTFMCOMMODITY_QUERY", @"DeleteMTFMCOMMODITY_QUERY", @"PublishMTFMCOMMODITY_QUERY", @"InvokeMTFMCOMMODITY_QUERY", @"InvokeMTFMCOMMODITY_QUERYResponse", @"QueryMTFMCOMMODITY_QUERYResponse", @"CreateMTFMCOMMODITY_QUERYResponse", 
@"SyncMTFMCOMMODITY_QUERYResponse", @"UpdateMTFMCOMMODITY_QUERYResponse", @"DeleteMTFMCOMMODITY_QUERYResponse"})]
    public sealed class MTFMVISIONFM_MTFMCOMMQUERY_www_ibm_com_maximo : Microsoft.XLANGs.BaseTypes.SchemaBase {
        
        [System.NonSerializedAttribute()]
        private static object _rawSchema;
        
        [System.NonSerializedAttribute()]
        private const string _strSchema = @"<?xml version=""1.0"" encoding=""utf-16""?>
<xs:schema xmlns=""http://www.ibm.com/maximo"" xmlns:b=""http://schemas.microsoft.com/BizTalk/2003"" attributeFormDefault=""unqualified"" elementFormDefault=""qualified"" targetNamespace=""http://www.ibm.com/maximo"" xmlns:xs=""http://www.w3.org/2001/XMLSchema"">
  <xs:simpleType name=""ProcessingActionType"">
    <xs:annotation>
      <xs:documentation>Enumerated List of Processing Actions supported by Maximo Services</xs:documentation>
    </xs:annotation>
    <xs:restriction base=""xs:token"">
      <xs:enumeration value=""Add"" />
      <xs:enumeration value=""Change"" />
      <xs:enumeration value=""Replace"" />
      <xs:enumeration value=""Delete"" />
      <xs:enumeration value=""AddChange"" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name=""OperandModeType"">
    <xs:annotation>
      <xs:documentation>Enumerated List of operand modes supported by Maximo Query</xs:documentation>
    </xs:annotation>
    <xs:restriction base=""xs:token"">
      <xs:enumeration value=""OR"" />
      <xs:enumeration value=""AND"" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name=""MboRelationshipType"">
    <xs:restriction base=""xs:string"" />
  </xs:simpleType>
  <xs:simpleType name=""EventType"">
    <xs:annotation>
      <xs:documentation>Boolean flag identifying if a published MOS was the result of an event. 1 implies event</xs:documentation>
    </xs:annotation>
    <xs:restriction base=""xs:boolean"">
      <xs:pattern value=""0|1"" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name=""ChangeIndicatorType"">
    <xs:annotation>
      <xs:documentation>Boolean flag identifying if a field has a new value. Applicable only for a MOS generated by an event</xs:documentation>
    </xs:annotation>
    <xs:restriction base=""xs:boolean"">
      <xs:pattern value=""1"" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name=""QueryOperatorType"">
    <xs:annotation>
      <xs:documentation>Operator identifying the QBE action to be performed on the field it is associated with</xs:documentation>
    </xs:annotation>
    <xs:restriction base=""xs:token"">
      <xs:enumeration value=""="" />
      <xs:enumeration value=""!="" />
      <xs:enumeration value=""&lt;"" />
      <xs:enumeration value=""&lt;="" />
      <xs:enumeration value=""&gt;"" />
      <xs:enumeration value=""&gt;="" />
      <xs:enumeration value=""EW"" />
      <xs:enumeration value=""SW"" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name=""BooleanType"">
    <xs:restriction base=""xs:boolean"">
      <xs:pattern value=""0|1"" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name=""MaximoVersionType"">
    <xs:annotation>
      <xs:documentation>This is a concatenated string that identifies the major version, minor version, build and dbbuild</xs:documentation>
    </xs:annotation>
    <xs:restriction base=""xs:string"" />
  </xs:simpleType>
  <xs:complexType name=""MXStringType"">
    <xs:simpleContent>
      <xs:extension base=""xs:string"">
        <xs:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXLangStringType"">
    <xs:simpleContent>
      <xs:extension base=""xs:string"">
        <xs:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
        <xs:attribute fixed=""1"" name=""languageEnabled"" type=""xs:boolean"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXDoubleType"">
    <xs:simpleContent>
      <xs:extension base=""xs:double"">
        <xs:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXFloatType"">
    <xs:simpleContent>
      <xs:extension base=""xs:float"">
        <xs:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXLongType"">
    <xs:simpleContent>
      <xs:extension base=""xs:long"">
        <xs:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXIntType"">
    <xs:simpleContent>
      <xs:extension base=""xs:int"">
        <xs:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXBooleanType"">
    <xs:simpleContent>
      <xs:extension base=""BooleanType"">
        <xs:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXDateTimeType"">
    <xs:simpleContent>
      <xs:extension base=""xs:dateTime"">
        <xs:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXBinaryType"">
    <xs:simpleContent>
      <xs:extension base=""xs:base64Binary"">
        <xs:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXCryptoType"">
    <xs:simpleContent>
      <xs:extension base=""xs:base64Binary"">
        <xs:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
        <xs:attribute default=""1"" name=""mxencrypted"" type=""BooleanType"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXGLComponentType"">
    <xs:simpleContent>
      <xs:extension base=""xs:string"">
        <xs:attribute name=""glorder"" use=""required"">
          <xs:simpleType>
            <xs:restriction base=""xs:int"">
              <xs:minInclusive value=""0"" />
              <xs:maxExclusive value=""20"" />
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXGLAccountType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" name=""VALUE"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""20"" name=""GLCOMP"" type=""MXGLComponentType"" />
    </xs:sequence>
    <xs:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
  </xs:complexType>
  <xs:complexType name=""MXDomainType"">
    <xs:simpleContent>
      <xs:extension base=""xs:string"">
        <xs:attribute name=""maxvalue"" type=""xs:string"" use=""optional"" />
        <xs:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXStringQueryType"">
    <xs:simpleContent>
      <xs:extension base=""xs:string"">
        <xs:attribute name=""operator"" type=""QueryOperatorType"" use=""optional"" />
        <xs:attribute name=""operandModeOR"" type=""xs:boolean"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXDoubleQueryType"">
    <xs:simpleContent>
      <xs:extension base=""xs:double"">
        <xs:attribute name=""operator"" type=""QueryOperatorType"" use=""optional"" />
        <xs:attribute name=""operandModeOR"" type=""xs:boolean"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXFloatQueryType"">
    <xs:simpleContent>
      <xs:extension base=""xs:float"">
        <xs:attribute name=""operator"" type=""QueryOperatorType"" use=""optional"" />
        <xs:attribute name=""operandModeOR"" type=""xs:boolean"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXLongQueryType"">
    <xs:simpleContent>
      <xs:extension base=""xs:string"">
        <xs:attribute name=""operator"" type=""QueryOperatorType"" use=""optional"" />
        <xs:attribute name=""operandModeOR"" type=""xs:boolean"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXIntQueryType"">
    <xs:simpleContent>
      <xs:extension base=""xs:int"">
        <xs:attribute name=""operator"" type=""QueryOperatorType"" use=""optional"" />
        <xs:attribute name=""operandModeOR"" type=""xs:boolean"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXBooleanQueryType"">
    <xs:simpleContent>
      <xs:extension base=""BooleanType"">
        <xs:attribute name=""operator"" type=""QueryOperatorType"" use=""optional"" />
        <xs:attribute name=""operandModeOR"" type=""xs:boolean"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXDateTimeQueryType"">
    <xs:simpleContent>
      <xs:extension base=""xs:dateTime"">
        <xs:attribute name=""operator"" type=""QueryOperatorType"" use=""optional"" />
        <xs:attribute name=""operandModeOR"" type=""xs:boolean"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXGLComponentQueryType"">
    <xs:simpleContent>
      <xs:extension base=""xs:string"">
        <xs:attribute name=""glorder"" use=""required"">
          <xs:simpleType>
            <xs:restriction base=""xs:int"">
              <xs:minInclusive value=""0"" />
              <xs:maxExclusive value=""20"" />
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXGLAccountQueryType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" name=""VALUE"" type=""xs:string"" />
    </xs:sequence>
    <xs:attribute name=""operator"" type=""QueryOperatorType"" use=""optional"" />
    <xs:attribute name=""operandModeOR"" type=""xs:boolean"" use=""optional"" />
  </xs:complexType>
  <xs:complexType name=""MXDomainQueryType"">
    <xs:simpleContent>
      <xs:extension base=""xs:string"">
        <xs:attribute name=""maxvalue"" type=""xs:string"" use=""optional"" />
        <xs:attribute name=""operator"" type=""QueryOperatorType"" use=""optional"" />
        <xs:attribute name=""operandModeOR"" type=""xs:boolean"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:attributeGroup name=""ObjectStructurePropertyGroup"">
    <xs:attribute name=""action"" type=""ProcessingActionType"" use=""optional"" />
    <xs:attribute name=""relationship"" type=""xs:string"" use=""optional"" />
    <xs:attribute name=""deleteForInsert"" type=""xs:string"" use=""optional"" />
  </xs:attributeGroup>
  <xs:attributeGroup name=""CommonContentGroup"">
    <xs:attribute name=""creationDateTime"" type=""xs:dateTime"" use=""optional"" />
    <xs:attribute name=""baseLanguage"" type=""xs:string"" use=""optional"" />
    <xs:attribute name=""transLanguage"" type=""xs:string"" use=""optional"" />
    <xs:attribute name=""messageID"" type=""xs:string"" use=""optional"" />
    <xs:attribute name=""maximoVersion"" type=""MaximoVersionType"" use=""optional"" />
  </xs:attributeGroup>
  <xs:attributeGroup name=""PublishingContentGroup"">
    <xs:attribute default=""0"" name=""event"" type=""EventType"" use=""optional"" />
  </xs:attributeGroup>
  <xs:attributeGroup name=""QueryContentGroup"">
    <xs:attribute default=""0"" name=""uniqueResult"" type=""BooleanType"" use=""optional"" />
    <xs:attribute name=""maxItems"" type=""xs:positiveInteger"" use=""optional"" />
    <xs:attribute default=""0"" name=""rsStart"" type=""xs:integer"" use=""optional"" />
  </xs:attributeGroup>
  <xs:attributeGroup name=""QueryClausePropertyGroup"">
    <xs:attribute name=""orderby"" type=""xs:string"" use=""optional"" />
    <xs:attribute default=""AND"" name=""operandMode"" type=""OperandModeType"" use=""optional"" />
  </xs:attributeGroup>
  <xs:attributeGroup name=""ResponseContentGroup"">
    <xs:attribute name=""rsStart"" type=""xs:integer"" use=""optional"" />
    <xs:attribute name=""rsCount"" type=""xs:integer"" use=""optional"" />
    <xs:attribute name=""rsTotal"" type=""xs:integer"" use=""optional"" />
  </xs:attributeGroup>
  <xs:complexType name=""COMMODITIESKeyType"">
    <xs:sequence>
      <xs:element name=""COMMODITY"" type=""MXStringType"">
        <xs:annotation>
          <xs:documentation>Unique Key Component</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name=""ITEMSETID"" type=""MXStringType"">
        <xs:annotation>
          <xs:documentation>Unique Key Component</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name=""COMMODITIESObjectType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" name=""COMMODITY"" type=""MXStringType"">
        <xs:annotation>
          <xs:documentation>Unique Key Component</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs=""0"" name=""DESCRIPTION"" type=""MXStringType"">
        <xs:annotation>
          <xs:documentation>Multiple languages supported</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs=""0"" name=""PARENT"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""ISSERVICE"" type=""MXBooleanType"" />
      <xs:element minOccurs=""0"" name=""SERVICETYPE"" type=""MXDomainType"" />
      <xs:element minOccurs=""0"" name=""ITEMSETID"" type=""MXStringType"">
        <xs:annotation>
          <xs:documentation>Unique Key Component</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs=""0"" name=""COMMODITIESID"" nillable=""true"" type=""MXLongType"" />
      <xs:element minOccurs=""0"" name=""OWNER"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""OWNERGROUP"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""LANGCODE"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""HASLD"" type=""MXBooleanType"" />
    </xs:sequence>
    <xs:attribute name=""action"" type=""ProcessingActionType"" use=""optional"" />
  </xs:complexType>
  <xs:complexType name=""COMMODITIESMboKeyType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" name=""COMMODITIES"" type=""COMMODITIESKeyType"" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name=""COMMODITIESMboKeySetType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""COMMODITIES"" type=""COMMODITIESKeyType"" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name=""COMMODITIESMboSetType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""COMMODITIES"" type=""COMMODITIESObjectType"" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name=""COMMODITIESMboType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" name=""COMMODITIES"" type=""COMMODITIESObjectType"" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name=""COMMODITIESMboQueryType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" name=""WHERE"" type=""xs:string"" />
      <xs:element minOccurs=""0"" name=""COMMODITIES"">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""COMMODITY"" type=""MXStringQueryType"">
              <xs:annotation>
                <xs:documentation>Unique Key Component</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""DESCRIPTION"" type=""MXStringQueryType"">
              <xs:annotation>
                <xs:documentation>Multiple languages supported</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""PARENT"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""ISSERVICE"" type=""MXBooleanQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""SERVICETYPE"" type=""MXDomainQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""ITEMSETID"" type=""MXStringQueryType"">
              <xs:annotation>
                <xs:documentation>Unique Key Component</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""COMMODITIESID"" nillable=""true"" type=""MXLongQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""OWNER"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""OWNERGROUP"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""LANGCODE"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""HASLD"" type=""MXBooleanQueryType"" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attributeGroup ref=""QueryClausePropertyGroup"" />
  </xs:complexType>
  <xs:element name=""COMMODITIESMbo"" type=""COMMODITIESMboType"" />
  <xs:element name=""COMMODITIESMboSet"" type=""COMMODITIESMboSetType"" />
  <xs:element name=""COMMODITIESMboKey"" type=""COMMODITIESMboKeyType"" />
  <xs:element name=""COMMODITIESMboKeySet"" type=""COMMODITIESMboKeySetType"" />
  <xs:element name=""COMMODITIESMboQuery"" type=""COMMODITIESMboQueryType"" />
  <xs:complexType name=""MTFMCOMMODITY_QUERY_COMMODITIESType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" name=""MAXINTERRORMSG"" type=""xs:string"" />
      <xs:element minOccurs=""0"" name=""COMMODITIESID"" nillable=""true"" type=""MXLongType"" />
      <xs:element minOccurs=""0"" name=""COMMODITY"" type=""MXStringType"">
        <xs:annotation>
          <xs:documentation>Unique Key Component</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs=""0"" name=""DESCRIPTION"" type=""MXStringType"">
        <xs:annotation>
          <xs:documentation>Multiple languages supported</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs=""0"" name=""ISSERVICE"" type=""MXBooleanType"" />
      <xs:element minOccurs=""0"" name=""ITEMSETID"" type=""MXStringType"">
        <xs:annotation>
          <xs:documentation>Unique Key Component</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs=""0"" name=""OWNER"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""OWNERGROUP"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""PARENT"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""SERVICETYPE"" type=""MXDomainType"" />
    </xs:sequence>
    <xs:attributeGroup ref=""ObjectStructurePropertyGroup"" />
    <xs:attribute name=""transLanguage"" type=""xs:string"" use=""optional"" />
  </xs:complexType>
  <xs:complexType name=""MTFMCOMMODITY_QUERYType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" name=""COMMODITIES"" type=""MTFMCOMMODITY_QUERY_COMMODITIESType"" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name=""MTFMCOMMODITY_QUERYSetType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""COMMODITIES"" type=""MTFMCOMMODITY_QUERY_COMMODITIESType"" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name=""MTFMCOMMODITY_QUERYQueryType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" name=""WHERE"" type=""xs:string"" />
      <xs:element minOccurs=""0"" name=""COMMODITIES"">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""COMMODITIESID"" nillable=""true"" type=""MXLongQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""COMMODITY"" type=""MXStringQueryType"">
              <xs:annotation>
                <xs:documentation>Unique Key Component</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""DESCRIPTION"" type=""MXStringQueryType"">
              <xs:annotation>
                <xs:documentation>Multiple languages supported</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""ISSERVICE"" type=""MXBooleanQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""ITEMSETID"" type=""MXStringQueryType"">
              <xs:annotation>
                <xs:documentation>Unique Key Component</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""OWNER"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""OWNERGROUP"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""PARENT"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""SERVICETYPE"" type=""MXDomainQueryType"" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attributeGroup ref=""QueryClausePropertyGroup"" />
  </xs:complexType>
  <xs:complexType name=""MTFMCOMMODITY_QUERYCombinedKeySetType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""COMMODITIES"">
        <xs:complexType>
          <xs:sequence>
            <xs:element name=""COMMODITY"" type=""MXStringType"">
              <xs:annotation>
                <xs:documentation>Unique Key Component</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element name=""ITEMSETID"" type=""MXStringType"">
              <xs:annotation>
                <xs:documentation>Unique Key Component</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element name=""COMMODITIESID"" nillable=""true"" type=""MXLongType"" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name=""MTFMCOMMODITY_QUERY"" type=""MTFMCOMMODITY_QUERYType"" />
  <xs:element name=""MTFMCOMMODITY_QUERYSet"" type=""MTFMCOMMODITY_QUERYSetType"" />
  <xs:element name=""MTFMCOMMODITY_QUERYQuery"" type=""MTFMCOMMODITY_QUERYQueryType"" />
  <xs:complexType name=""CreateMTFMCOMMODITY_QUERYType"">
    <xs:sequence>
      <xs:element ref=""MTFMCOMMODITY_QUERYSet"" />
    </xs:sequence>
    <xs:attributeGroup ref=""CommonContentGroup"" />
  </xs:complexType>
  <xs:complexType name=""InvokeMTFMCOMMODITY_QUERYType"">
    <xs:sequence>
      <xs:element ref=""MTFMCOMMODITY_QUERYSet"" />
    </xs:sequence>
    <xs:attributeGroup ref=""CommonContentGroup"" />
  </xs:complexType>
  <xs:complexType name=""QueryMTFMCOMMODITY_QUERYType"">
    <xs:sequence>
      <xs:element ref=""MTFMCOMMODITY_QUERYQuery"" />
    </xs:sequence>
    <xs:attributeGroup ref=""CommonContentGroup"" />
    <xs:attributeGroup ref=""QueryContentGroup"" />
  </xs:complexType>
  <xs:complexType name=""SyncMTFMCOMMODITY_QUERYType"">
    <xs:sequence>
      <xs:element ref=""MTFMCOMMODITY_QUERYSet"" />
    </xs:sequence>
    <xs:attributeGroup ref=""CommonContentGroup"" />
  </xs:complexType>
  <xs:complexType name=""PublishMTFMCOMMODITY_QUERYType"">
    <xs:sequence>
      <xs:element ref=""MTFMCOMMODITY_QUERYSet"" />
    </xs:sequence>
    <xs:attributeGroup ref=""CommonContentGroup"" />
    <xs:attributeGroup ref=""PublishingContentGroup"" />
  </xs:complexType>
  <xs:complexType name=""UpdateMTFMCOMMODITY_QUERYType"">
    <xs:sequence>
      <xs:element ref=""MTFMCOMMODITY_QUERYSet"" />
    </xs:sequence>
    <xs:attributeGroup ref=""CommonContentGroup"" />
  </xs:complexType>
  <xs:complexType name=""DeleteMTFMCOMMODITY_QUERYType"">
    <xs:sequence>
      <xs:element ref=""MTFMCOMMODITY_QUERYSet"" />
    </xs:sequence>
    <xs:attributeGroup ref=""CommonContentGroup"" />
  </xs:complexType>
  <xs:complexType name=""InvokeMTFMCOMMODITY_QUERYResponseType"">
    <xs:sequence>
      <xs:element ref=""MTFMCOMMODITY_QUERYSet"" />
    </xs:sequence>
    <xs:attributeGroup ref=""CommonContentGroup"" />
  </xs:complexType>
  <xs:complexType name=""CreateMTFMCOMMODITY_QUERYResponseType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" ref=""COMMODITIESMboKeySet"" />
    </xs:sequence>
    <xs:attributeGroup ref=""CommonContentGroup"" />
  </xs:complexType>
  <xs:complexType name=""QueryMTFMCOMMODITY_QUERYResponseType"">
    <xs:sequence>
      <xs:element ref=""MTFMCOMMODITY_QUERYSet"" />
    </xs:sequence>
    <xs:attributeGroup ref=""CommonContentGroup"" />
    <xs:attributeGroup ref=""ResponseContentGroup"" />
  </xs:complexType>
  <xs:complexType name=""SyncMTFMCOMMODITY_QUERYResponseType"">
    <xs:sequence />
    <xs:attributeGroup ref=""CommonContentGroup"" />
  </xs:complexType>
  <xs:complexType name=""DeleteMTFMCOMMODITY_QUERYResponseType"">
    <xs:sequence />
    <xs:attributeGroup ref=""CommonContentGroup"" />
  </xs:complexType>
  <xs:complexType name=""UpdateMTFMCOMMODITY_QUERYResponseType"">
    <xs:sequence />
    <xs:attributeGroup ref=""CommonContentGroup"" />
  </xs:complexType>
  <xs:element name=""UpdateMTFMCOMMODITY_QUERY"" type=""UpdateMTFMCOMMODITY_QUERYType"" />
  <xs:element name=""QueryMTFMCOMMODITY_QUERY"" type=""QueryMTFMCOMMODITY_QUERYType"" />
  <xs:element name=""CreateMTFMCOMMODITY_QUERY"" type=""CreateMTFMCOMMODITY_QUERYType"" />
  <xs:element name=""SyncMTFMCOMMODITY_QUERY"" type=""SyncMTFMCOMMODITY_QUERYType"" />
  <xs:element name=""DeleteMTFMCOMMODITY_QUERY"" type=""DeleteMTFMCOMMODITY_QUERYType"" />
  <xs:element name=""PublishMTFMCOMMODITY_QUERY"" type=""PublishMTFMCOMMODITY_QUERYType"" />
  <xs:element name=""InvokeMTFMCOMMODITY_QUERY"" type=""InvokeMTFMCOMMODITY_QUERYType"" />
  <xs:element name=""InvokeMTFMCOMMODITY_QUERYResponse"" type=""InvokeMTFMCOMMODITY_QUERYResponseType"" />
  <xs:element name=""QueryMTFMCOMMODITY_QUERYResponse"" type=""QueryMTFMCOMMODITY_QUERYResponseType"" />
  <xs:element name=""CreateMTFMCOMMODITY_QUERYResponse"" type=""CreateMTFMCOMMODITY_QUERYResponseType"" />
  <xs:element name=""SyncMTFMCOMMODITY_QUERYResponse"" type=""SyncMTFMCOMMODITY_QUERYResponseType"" />
  <xs:element name=""UpdateMTFMCOMMODITY_QUERYResponse"" type=""UpdateMTFMCOMMODITY_QUERYResponseType"" />
  <xs:element name=""DeleteMTFMCOMMODITY_QUERYResponse"" type=""DeleteMTFMCOMMODITY_QUERYResponseType"" />
</xs:schema>";
        
        public MTFMVISIONFM_MTFMCOMMQUERY_www_ibm_com_maximo() {
        }
        
        public override string XmlContent {
            get {
                return _strSchema;
            }
        }
        
        public override string[] RootNodes {
            get {
                string[] _RootElements = new string [21];
                _RootElements[0] = "COMMODITIESMbo";
                _RootElements[1] = "COMMODITIESMboSet";
                _RootElements[2] = "COMMODITIESMboKey";
                _RootElements[3] = "COMMODITIESMboKeySet";
                _RootElements[4] = "COMMODITIESMboQuery";
                _RootElements[5] = "MTFMCOMMODITY_QUERY";
                _RootElements[6] = "MTFMCOMMODITY_QUERYSet";
                _RootElements[7] = "MTFMCOMMODITY_QUERYQuery";
                _RootElements[8] = "UpdateMTFMCOMMODITY_QUERY";
                _RootElements[9] = "QueryMTFMCOMMODITY_QUERY";
                _RootElements[10] = "CreateMTFMCOMMODITY_QUERY";
                _RootElements[11] = "SyncMTFMCOMMODITY_QUERY";
                _RootElements[12] = "DeleteMTFMCOMMODITY_QUERY";
                _RootElements[13] = "PublishMTFMCOMMODITY_QUERY";
                _RootElements[14] = "InvokeMTFMCOMMODITY_QUERY";
                _RootElements[15] = "InvokeMTFMCOMMODITY_QUERYResponse";
                _RootElements[16] = "QueryMTFMCOMMODITY_QUERYResponse";
                _RootElements[17] = "CreateMTFMCOMMODITY_QUERYResponse";
                _RootElements[18] = "SyncMTFMCOMMODITY_QUERYResponse";
                _RootElements[19] = "UpdateMTFMCOMMODITY_QUERYResponse";
                _RootElements[20] = "DeleteMTFMCOMMODITY_QUERYResponse";
                return _RootElements;
            }
        }
        
        protected override object RawSchema {
            get {
                return _rawSchema;
            }
            set {
                _rawSchema = value;
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"COMMODITIESMbo")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"COMMODITIESMbo"})]
        public sealed class COMMODITIESMbo : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public COMMODITIESMbo() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "COMMODITIESMbo";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"COMMODITIESMboSet")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"COMMODITIESMboSet"})]
        public sealed class COMMODITIESMboSet : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public COMMODITIESMboSet() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "COMMODITIESMboSet";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"COMMODITIESMboKey")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"COMMODITIESMboKey"})]
        public sealed class COMMODITIESMboKey : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public COMMODITIESMboKey() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "COMMODITIESMboKey";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"COMMODITIESMboKeySet")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"COMMODITIESMboKeySet"})]
        public sealed class COMMODITIESMboKeySet : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public COMMODITIESMboKeySet() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "COMMODITIESMboKeySet";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"COMMODITIESMboQuery")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"COMMODITIESMboQuery"})]
        public sealed class COMMODITIESMboQuery : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public COMMODITIESMboQuery() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "COMMODITIESMboQuery";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"MTFMCOMMODITY_QUERY")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"MTFMCOMMODITY_QUERY"})]
        public sealed class MTFMCOMMODITY_QUERY : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public MTFMCOMMODITY_QUERY() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "MTFMCOMMODITY_QUERY";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"MTFMCOMMODITY_QUERYSet")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"MTFMCOMMODITY_QUERYSet"})]
        public sealed class MTFMCOMMODITY_QUERYSet : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public MTFMCOMMODITY_QUERYSet() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "MTFMCOMMODITY_QUERYSet";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"MTFMCOMMODITY_QUERYQuery")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"MTFMCOMMODITY_QUERYQuery"})]
        public sealed class MTFMCOMMODITY_QUERYQuery : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public MTFMCOMMODITY_QUERYQuery() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "MTFMCOMMODITY_QUERYQuery";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"UpdateMTFMCOMMODITY_QUERY")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"UpdateMTFMCOMMODITY_QUERY"})]
        public sealed class UpdateMTFMCOMMODITY_QUERY : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public UpdateMTFMCOMMODITY_QUERY() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "UpdateMTFMCOMMODITY_QUERY";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"QueryMTFMCOMMODITY_QUERY")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"QueryMTFMCOMMODITY_QUERY"})]
        public sealed class QueryMTFMCOMMODITY_QUERY : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public QueryMTFMCOMMODITY_QUERY() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "QueryMTFMCOMMODITY_QUERY";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"CreateMTFMCOMMODITY_QUERY")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"CreateMTFMCOMMODITY_QUERY"})]
        public sealed class CreateMTFMCOMMODITY_QUERY : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public CreateMTFMCOMMODITY_QUERY() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "CreateMTFMCOMMODITY_QUERY";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"SyncMTFMCOMMODITY_QUERY")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"SyncMTFMCOMMODITY_QUERY"})]
        public sealed class SyncMTFMCOMMODITY_QUERY : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public SyncMTFMCOMMODITY_QUERY() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "SyncMTFMCOMMODITY_QUERY";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"DeleteMTFMCOMMODITY_QUERY")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"DeleteMTFMCOMMODITY_QUERY"})]
        public sealed class DeleteMTFMCOMMODITY_QUERY : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public DeleteMTFMCOMMODITY_QUERY() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "DeleteMTFMCOMMODITY_QUERY";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"PublishMTFMCOMMODITY_QUERY")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"PublishMTFMCOMMODITY_QUERY"})]
        public sealed class PublishMTFMCOMMODITY_QUERY : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public PublishMTFMCOMMODITY_QUERY() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "PublishMTFMCOMMODITY_QUERY";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"InvokeMTFMCOMMODITY_QUERY")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"InvokeMTFMCOMMODITY_QUERY"})]
        public sealed class InvokeMTFMCOMMODITY_QUERY : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public InvokeMTFMCOMMODITY_QUERY() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "InvokeMTFMCOMMODITY_QUERY";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"InvokeMTFMCOMMODITY_QUERYResponse")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"InvokeMTFMCOMMODITY_QUERYResponse"})]
        public sealed class InvokeMTFMCOMMODITY_QUERYResponse : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public InvokeMTFMCOMMODITY_QUERYResponse() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "InvokeMTFMCOMMODITY_QUERYResponse";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"QueryMTFMCOMMODITY_QUERYResponse")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"QueryMTFMCOMMODITY_QUERYResponse"})]
        public sealed class QueryMTFMCOMMODITY_QUERYResponse : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public QueryMTFMCOMMODITY_QUERYResponse() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "QueryMTFMCOMMODITY_QUERYResponse";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"CreateMTFMCOMMODITY_QUERYResponse")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"CreateMTFMCOMMODITY_QUERYResponse"})]
        public sealed class CreateMTFMCOMMODITY_QUERYResponse : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public CreateMTFMCOMMODITY_QUERYResponse() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "CreateMTFMCOMMODITY_QUERYResponse";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"SyncMTFMCOMMODITY_QUERYResponse")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"SyncMTFMCOMMODITY_QUERYResponse"})]
        public sealed class SyncMTFMCOMMODITY_QUERYResponse : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public SyncMTFMCOMMODITY_QUERYResponse() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "SyncMTFMCOMMODITY_QUERYResponse";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"UpdateMTFMCOMMODITY_QUERYResponse")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"UpdateMTFMCOMMODITY_QUERYResponse"})]
        public sealed class UpdateMTFMCOMMODITY_QUERYResponse : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public UpdateMTFMCOMMODITY_QUERYResponse() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "UpdateMTFMCOMMODITY_QUERYResponse";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"DeleteMTFMCOMMODITY_QUERYResponse")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"DeleteMTFMCOMMODITY_QUERYResponse"})]
        public sealed class DeleteMTFMCOMMODITY_QUERYResponse : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public DeleteMTFMCOMMODITY_QUERYResponse() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "DeleteMTFMCOMMODITY_QUERYResponse";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
    }
}
