namespace MFM.Lbg.Orcs.GenItems {
    using Microsoft.XLANGs.BaseTypes;
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.BizTalk.Schema.Compiler", "3.0.1.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [SchemaType(SchemaTypeEnum.Document)]
    [System.SerializableAttribute()]
    [SchemaRoots(new string[] {@"MXVISIONLOCQUERY", @"MXVISIONLOCQUERYSet", @"MXVISIONLOCQUERYQuery", @"LOCATIONSMbo", @"LOCATIONSMboSet", @"LOCATIONSMboKey", @"LOCATIONSMboKeySet", @"LOCATIONSMboQuery", @"UpdateMXVISIONLOCQUERY", @"QueryMXVISIONLOCQUERY", @"CreateMXVISIONLOCQUERY", @"SyncMXVISIONLOCQUERY", @"DeleteMXVISIONLOCQUERY", @"PublishMXVISIONLOCQUERY", @"InvokeMXVISIONLOCQUERY", @"InvokeMXVISIONLOCQUERYResponse", @"QueryMXVISIONLOCQUERYResponse", @"CreateMXVISIONLOCQUERYResponse", @"SyncMXVISIONLOCQUERYResponse", 
@"UpdateMXVISIONLOCQUERYResponse", @"DeleteMXVISIONLOCQUERYResponse"})]
    public sealed class MTFMVISIONFM_MTFMVISIONLOCQUERY_www_ibm_com_maximo : Microsoft.XLANGs.BaseTypes.SchemaBase {
        
        [System.NonSerializedAttribute()]
        private static object _rawSchema;
        
        [System.NonSerializedAttribute()]
        private const string _strSchema = @"<?xml version=""1.0"" encoding=""utf-16""?>
<xs:schema xmlns=""http://www.ibm.com/maximo"" xmlns:b=""http://schemas.microsoft.com/BizTalk/2003"" attributeFormDefault=""unqualified"" elementFormDefault=""qualified"" targetNamespace=""http://www.ibm.com/maximo"" xmlns:xs=""http://www.w3.org/2001/XMLSchema"">
  <xs:simpleType name=""ProcessingActionType"">
    <xs:annotation>
      <xs:documentation>Enumerated List of Processing Actions supported by Maximo Services</xs:documentation>
    </xs:annotation>
    <xs:restriction base=""xs:token"">
      <xs:enumeration value=""Add"" />
      <xs:enumeration value=""Change"" />
      <xs:enumeration value=""Replace"" />
      <xs:enumeration value=""Delete"" />
      <xs:enumeration value=""AddChange"" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name=""OperandModeType"">
    <xs:annotation>
      <xs:documentation>Enumerated List of operand modes supported by Maximo Query</xs:documentation>
    </xs:annotation>
    <xs:restriction base=""xs:token"">
      <xs:enumeration value=""OR"" />
      <xs:enumeration value=""AND"" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name=""MboRelationshipType"">
    <xs:restriction base=""xs:string"" />
  </xs:simpleType>
  <xs:simpleType name=""EventType"">
    <xs:annotation>
      <xs:documentation>Boolean flag identifying if a published MOS was the result of an event. 1 implies event</xs:documentation>
    </xs:annotation>
    <xs:restriction base=""xs:boolean"">
      <xs:pattern value=""0|1"" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name=""ChangeIndicatorType"">
    <xs:annotation>
      <xs:documentation>Boolean flag identifying if a field has a new value. Applicable only for a MOS generated by an event</xs:documentation>
    </xs:annotation>
    <xs:restriction base=""xs:boolean"">
      <xs:pattern value=""1"" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name=""QueryOperatorType"">
    <xs:annotation>
      <xs:documentation>Operator identifying the QBE action to be performed on the field it is associated with</xs:documentation>
    </xs:annotation>
    <xs:restriction base=""xs:token"">
      <xs:enumeration value=""="" />
      <xs:enumeration value=""!="" />
      <xs:enumeration value=""&lt;"" />
      <xs:enumeration value=""&lt;="" />
      <xs:enumeration value=""&gt;"" />
      <xs:enumeration value=""&gt;="" />
      <xs:enumeration value=""EW"" />
      <xs:enumeration value=""SW"" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name=""BooleanType"">
    <xs:restriction base=""xs:boolean"">
      <xs:pattern value=""0|1"" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name=""MaximoVersionType"">
    <xs:annotation>
      <xs:documentation>This is a concatenated string that identifies the major version, minor version, build and dbbuild</xs:documentation>
    </xs:annotation>
    <xs:restriction base=""xs:string"" />
  </xs:simpleType>
  <xs:complexType name=""MXStringType"">
    <xs:simpleContent>
      <xs:extension base=""xs:string"">
        <xs:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXLangStringType"">
    <xs:simpleContent>
      <xs:extension base=""xs:string"">
        <xs:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
        <xs:attribute fixed=""1"" name=""languageEnabled"" type=""xs:boolean"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXDoubleType"">
    <xs:simpleContent>
      <xs:extension base=""xs:double"">
        <xs:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXFloatType"">
    <xs:simpleContent>
      <xs:extension base=""xs:float"">
        <xs:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXLongType"">
    <xs:simpleContent>
      <xs:extension base=""xs:long"">
        <xs:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXIntType"">
    <xs:simpleContent>
      <xs:extension base=""xs:int"">
        <xs:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXBooleanType"">
    <xs:simpleContent>
      <xs:extension base=""BooleanType"">
        <xs:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXDateTimeType"">
    <xs:simpleContent>
      <xs:extension base=""xs:dateTime"">
        <xs:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXBinaryType"">
    <xs:simpleContent>
      <xs:extension base=""xs:base64Binary"">
        <xs:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXCryptoType"">
    <xs:simpleContent>
      <xs:extension base=""xs:base64Binary"">
        <xs:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
        <xs:attribute default=""1"" name=""mxencrypted"" type=""BooleanType"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXGLComponentType"">
    <xs:simpleContent>
      <xs:extension base=""xs:string"">
        <xs:attribute name=""glorder"" use=""required"">
          <xs:simpleType>
            <xs:restriction base=""xs:int"">
              <xs:minInclusive value=""0"" />
              <xs:maxExclusive value=""20"" />
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXGLAccountType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" name=""VALUE"" type=""xs:string"" />
      <xs:element minOccurs=""0"" maxOccurs=""20"" name=""GLCOMP"" type=""MXGLComponentType"" />
    </xs:sequence>
    <xs:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
  </xs:complexType>
  <xs:complexType name=""MXDomainType"">
    <xs:simpleContent>
      <xs:extension base=""xs:string"">
        <xs:attribute name=""maxvalue"" type=""xs:string"" use=""optional"" />
        <xs:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXStringQueryType"">
    <xs:simpleContent>
      <xs:extension base=""xs:string"">
        <xs:attribute name=""operator"" type=""QueryOperatorType"" use=""optional"" />
        <xs:attribute name=""operandModeOR"" type=""xs:boolean"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXDoubleQueryType"">
    <xs:simpleContent>
      <xs:extension base=""xs:double"">
        <xs:attribute name=""operator"" type=""QueryOperatorType"" use=""optional"" />
        <xs:attribute name=""operandModeOR"" type=""xs:boolean"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXFloatQueryType"">
    <xs:simpleContent>
      <xs:extension base=""xs:float"">
        <xs:attribute name=""operator"" type=""QueryOperatorType"" use=""optional"" />
        <xs:attribute name=""operandModeOR"" type=""xs:boolean"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXLongQueryType"">
    <xs:simpleContent>
      <xs:extension base=""xs:string"">
        <xs:attribute name=""operator"" type=""QueryOperatorType"" use=""optional"" />
        <xs:attribute name=""operandModeOR"" type=""xs:boolean"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXIntQueryType"">
    <xs:simpleContent>
      <xs:extension base=""xs:int"">
        <xs:attribute name=""operator"" type=""QueryOperatorType"" use=""optional"" />
        <xs:attribute name=""operandModeOR"" type=""xs:boolean"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXBooleanQueryType"">
    <xs:simpleContent>
      <xs:extension base=""BooleanType"">
        <xs:attribute name=""operator"" type=""QueryOperatorType"" use=""optional"" />
        <xs:attribute name=""operandModeOR"" type=""xs:boolean"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXDateTimeQueryType"">
    <xs:simpleContent>
      <xs:extension base=""xs:dateTime"">
        <xs:attribute name=""operator"" type=""QueryOperatorType"" use=""optional"" />
        <xs:attribute name=""operandModeOR"" type=""xs:boolean"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXGLComponentQueryType"">
    <xs:simpleContent>
      <xs:extension base=""xs:string"">
        <xs:attribute name=""glorder"" use=""required"">
          <xs:simpleType>
            <xs:restriction base=""xs:int"">
              <xs:minInclusive value=""0"" />
              <xs:maxExclusive value=""20"" />
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name=""MXGLAccountQueryType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" name=""VALUE"" type=""xs:string"" />
    </xs:sequence>
    <xs:attribute name=""operator"" type=""QueryOperatorType"" use=""optional"" />
    <xs:attribute name=""operandModeOR"" type=""xs:boolean"" use=""optional"" />
  </xs:complexType>
  <xs:complexType name=""MXDomainQueryType"">
    <xs:simpleContent>
      <xs:extension base=""xs:string"">
        <xs:attribute name=""maxvalue"" type=""xs:string"" use=""optional"" />
        <xs:attribute name=""operator"" type=""QueryOperatorType"" use=""optional"" />
        <xs:attribute name=""operandModeOR"" type=""xs:boolean"" use=""optional"" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:attributeGroup name=""ObjectStructurePropertyGroup"">
    <xs:attribute name=""action"" type=""ProcessingActionType"" use=""optional"" />
    <xs:attribute name=""relationship"" type=""xs:string"" use=""optional"" />
    <xs:attribute name=""deleteForInsert"" type=""xs:string"" use=""optional"" />
  </xs:attributeGroup>
  <xs:attributeGroup name=""CommonContentGroup"">
    <xs:attribute name=""creationDateTime"" type=""xs:dateTime"" use=""optional"" />
    <xs:attribute name=""baseLanguage"" type=""xs:string"" use=""optional"" />
    <xs:attribute name=""transLanguage"" type=""xs:string"" use=""optional"" />
    <xs:attribute name=""messageID"" type=""xs:string"" use=""optional"" />
    <xs:attribute name=""maximoVersion"" type=""MaximoVersionType"" use=""optional"" />
  </xs:attributeGroup>
  <xs:attributeGroup name=""PublishingContentGroup"">
    <xs:attribute default=""0"" name=""event"" type=""EventType"" use=""optional"" />
  </xs:attributeGroup>
  <xs:attributeGroup name=""QueryContentGroup"">
    <xs:attribute default=""0"" name=""uniqueResult"" type=""BooleanType"" use=""optional"" />
    <xs:attribute name=""maxItems"" type=""xs:positiveInteger"" use=""optional"" />
    <xs:attribute default=""0"" name=""rsStart"" type=""xs:integer"" use=""optional"" />
  </xs:attributeGroup>
  <xs:attributeGroup name=""QueryClausePropertyGroup"">
    <xs:attribute name=""orderby"" type=""xs:string"" use=""optional"" />
    <xs:attribute default=""AND"" name=""operandMode"" type=""OperandModeType"" use=""optional"" />
  </xs:attributeGroup>
  <xs:attributeGroup name=""ResponseContentGroup"">
    <xs:attribute name=""rsStart"" type=""xs:integer"" use=""optional"" />
    <xs:attribute name=""rsCount"" type=""xs:integer"" use=""optional"" />
    <xs:attribute name=""rsTotal"" type=""xs:integer"" use=""optional"" />
  </xs:attributeGroup>
  <xs:complexType name=""MXVISIONLOCQUERY_LOCATIONSType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" name=""MAXINTERRORMSG"" type=""xs:string"" />
      <xs:element minOccurs=""0"" name=""DESCRIPTION"" type=""MXStringType"">
        <xs:annotation>
          <xs:documentation>Multiple languages supported</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs=""0"" name=""DESCRIPTION_LONGDESCRIPTION"" type=""MXStringType"">
        <xs:annotation>
          <xs:documentation>Multiple languages supported</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs=""0"" name=""DISABLED"" type=""MXBooleanType"" />
      <xs:element minOccurs=""0"" name=""LOCATION"" type=""MXStringType"">
        <xs:annotation>
          <xs:documentation>Unique Key Component</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs=""0"" name=""LOCATIONSID"" nillable=""true"" type=""MXLongType"" />
      <xs:element minOccurs=""0"" name=""MTFMBLDGCLASS1"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""MTFMBLDGCLASS2"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""MTFMLOCLVL"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""MTFMLOCPOS"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""MTFMPMJOB"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""MTFMPORTFOLIO"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""MTFMSOURCESYS"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""MTFMSUPER"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""MTFM_PMBPN"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""MTFM_RWBPN"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""ORGID"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""PARENT"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""SITEID"" type=""MXStringType"">
        <xs:annotation>
          <xs:documentation>Unique Key Component</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs=""0"" name=""STATUS"" type=""MXDomainType"" />
      <xs:element minOccurs=""0"" name=""SYSTEMID"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""TYPE"" type=""MXStringType"" />
    </xs:sequence>
    <xs:attributeGroup ref=""ObjectStructurePropertyGroup"" />
    <xs:attribute name=""transLanguage"" type=""xs:string"" use=""optional"" />
  </xs:complexType>
  <xs:complexType name=""MXVISIONLOCQUERYType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" name=""LOCATIONS"" type=""MXVISIONLOCQUERY_LOCATIONSType"" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name=""MXVISIONLOCQUERYSetType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""LOCATIONS"" type=""MXVISIONLOCQUERY_LOCATIONSType"" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name=""MXVISIONLOCQUERYQueryType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" name=""WHERE"" type=""xs:string"" />
      <xs:element minOccurs=""0"" name=""LOCATIONS"">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""DESCRIPTION"" type=""MXStringQueryType"">
              <xs:annotation>
                <xs:documentation>Multiple languages supported</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""DISABLED"" type=""MXBooleanQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""LOCATION"" type=""MXStringQueryType"">
              <xs:annotation>
                <xs:documentation>Unique Key Component</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""LOCATIONSID"" nillable=""true"" type=""MXLongQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFMBLDGCLASS1"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFMBLDGCLASS2"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFMLOCLVL"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFMLOCPOS"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFMPMJOB"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFMPORTFOLIO"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFMSOURCESYS"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFMSUPER"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFM_PMBPN"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFM_RWBPN"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""ORGID"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""SITEID"" type=""MXStringQueryType"">
              <xs:annotation>
                <xs:documentation>Unique Key Component</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""STATUS"" type=""MXDomainQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""TYPE"" type=""MXStringQueryType"" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attributeGroup ref=""QueryClausePropertyGroup"" />
  </xs:complexType>
  <xs:complexType name=""MXVISIONLOCQUERYCombinedKeySetType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""LOCATIONS"">
        <xs:complexType>
          <xs:sequence>
            <xs:element name=""SITEID"" type=""MXStringType"">
              <xs:annotation>
                <xs:documentation>Unique Key Component</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element name=""LOCATION"" type=""MXStringType"">
              <xs:annotation>
                <xs:documentation>Unique Key Component</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element name=""LOCATIONSID"" nillable=""true"" type=""MXLongType"" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name=""MXVISIONLOCQUERY"" type=""MXVISIONLOCQUERYType"" />
  <xs:element name=""MXVISIONLOCQUERYSet"" type=""MXVISIONLOCQUERYSetType"" />
  <xs:element name=""MXVISIONLOCQUERYQuery"" type=""MXVISIONLOCQUERYQueryType"" />
  <xs:complexType name=""LOCATIONSKeyType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" name=""SITEID"" type=""MXStringType"">
        <xs:annotation>
          <xs:documentation>Unique Key Component</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name=""LOCATION"" type=""MXStringType"">
        <xs:annotation>
          <xs:documentation>Unique Key Component</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name=""LOCATIONSObjectType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" name=""LOCATION"" type=""MXStringType"">
        <xs:annotation>
          <xs:documentation>Unique Key Component</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs=""0"" name=""DESCRIPTION"" type=""MXStringType"">
        <xs:annotation>
          <xs:documentation>Multiple languages supported</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs=""0"" name=""TYPE"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""CONTROLACC"" type=""MXGLAccountType"" />
      <xs:element minOccurs=""0"" name=""GLACCOUNT"" type=""MXGLAccountType"" />
      <xs:element minOccurs=""0"" name=""PURCHVARACC"" type=""MXGLAccountType"" />
      <xs:element minOccurs=""0"" name=""INVOICEVARACC"" type=""MXGLAccountType"" />
      <xs:element minOccurs=""0"" name=""CURVARACC"" type=""MXGLAccountType"" />
      <xs:element minOccurs=""0"" name=""SHRINKAGEACC"" type=""MXGLAccountType"" />
      <xs:element minOccurs=""0"" name=""INVCOSTADJACC"" type=""MXGLAccountType"" />
      <xs:element minOccurs=""0"" name=""RECEIPTVARACC"" type=""MXGLAccountType"" />
      <xs:element minOccurs=""0"" name=""CHANGEBY"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""CHANGEDATE"" nillable=""true"" type=""MXDateTimeType"" />
      <xs:element minOccurs=""0"" name=""DISABLED"" type=""MXBooleanType"" />
      <xs:element minOccurs=""0"" name=""OLDCONTROLACC"" type=""MXGLAccountType"" />
      <xs:element minOccurs=""0"" name=""OLDSHRINKAGEACC"" type=""MXGLAccountType"" />
      <xs:element minOccurs=""0"" name=""OLDINVCOSTADJACC"" type=""MXGLAccountType"" />
      <xs:element minOccurs=""0"" name=""CLASSSTRUCTUREID"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""GISPARAM1"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""GISPARAM2"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""GISPARAM3"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""SOURCESYSID"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""OWNERSYSID"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""EXTERNALREFID"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""SENDERSYSID"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""SITEID"" type=""MXStringType"">
        <xs:annotation>
          <xs:documentation>Unique Key Component</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs=""0"" name=""ORGID"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""INTLABREC"" type=""MXGLAccountType"" />
      <xs:element minOccurs=""0"" name=""ISDEFAULT"" type=""MXBooleanType"" />
      <xs:element minOccurs=""0"" name=""SHIPTOADDRESSCODE"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""SHIPTOLABORCODE"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""BILLTOADDRESSCODE"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""BILLTOLABORCODE"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""STATUS"" type=""MXDomainType"" />
      <xs:element minOccurs=""0"" name=""SERVICEADDRESSCODE"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""LOCATIONSID"" nillable=""true"" type=""MXLongType"" />
      <xs:element minOccurs=""0"" name=""USEINPOPR"" type=""MXBooleanType"" />
      <xs:element minOccurs=""0"" name=""TOOLCONTROLACC"" type=""MXGLAccountType"" />
      <xs:element minOccurs=""0"" name=""LANGCODE"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""HASLD"" type=""MXBooleanType"" />
      <xs:element minOccurs=""0"" name=""AUTOWOGEN"" type=""MXBooleanType"" />
      <xs:element minOccurs=""0"" name=""STATUSDATE"" nillable=""true"" type=""MXDateTimeType"" />
      <xs:element minOccurs=""0"" name=""INVOWNER"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""ISREPAIRFACILITY"" type=""MXBooleanType"" />
      <xs:element minOccurs=""0"" name=""PLUSCDUEDATE"" nillable=""true"" type=""MXDateTimeType"" />
      <xs:element minOccurs=""0"" name=""PLUSCLOOP"" type=""MXBooleanType"" />
      <xs:element minOccurs=""0"" name=""PLUSCPMEXTDATE"" type=""MXBooleanType"" />
      <xs:element minOccurs=""0"" name=""MTFMBLDGCLASS1"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""MTFMBLDGCLASS2"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""MTFMPMJOB"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""MTFMPORTFOLIO"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""MTFMCONTNUM"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""MTFMLOCLVL"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""MTFMLOCPOS"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""CLIENTLOCREF"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""CONTRACTNO"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""MTFMCLIENTACC"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""MTFM_PMBPN"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""MTFM_RWBPN"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""MTFMSOURCESYS"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""MTFMCLNAME"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""MTFMCLPHONE"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""LOCOWNER"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""SUBOWNER"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""SUBOWNER2"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""LOCATTRIBUTE1"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""LOCATTRIBUTE2"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""LOCATTRIBUTE3"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""LOCATTRIBUTE4"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""LOCATTRIBUTE5"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""LOCATTRIBUTE6"" type=""MXStringType"" />
      <xs:element minOccurs=""0"" name=""MTFMSUPER"" type=""MXStringType"" />
    </xs:sequence>
    <xs:attribute name=""action"" type=""ProcessingActionType"" use=""optional"" />
  </xs:complexType>
  <xs:complexType name=""LOCATIONSMboKeyType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" name=""LOCATIONS"" type=""LOCATIONSKeyType"" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name=""LOCATIONSMboKeySetType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""LOCATIONS"" type=""LOCATIONSKeyType"" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name=""LOCATIONSMboSetType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""LOCATIONS"" type=""LOCATIONSObjectType"" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name=""LOCATIONSMboType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" name=""LOCATIONS"" type=""LOCATIONSObjectType"" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name=""LOCATIONSMboQueryType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" name=""WHERE"" type=""xs:string"" />
      <xs:element minOccurs=""0"" name=""LOCATIONS"">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""LOCATION"" type=""MXStringQueryType"">
              <xs:annotation>
                <xs:documentation>Unique Key Component</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""DESCRIPTION"" type=""MXStringQueryType"">
              <xs:annotation>
                <xs:documentation>Multiple languages supported</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""TYPE"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""CONTROLACC"" type=""MXGLAccountQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""GLACCOUNT"" type=""MXGLAccountQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""PURCHVARACC"" type=""MXGLAccountQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""INVOICEVARACC"" type=""MXGLAccountQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""CURVARACC"" type=""MXGLAccountQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""SHRINKAGEACC"" type=""MXGLAccountQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""INVCOSTADJACC"" type=""MXGLAccountQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""RECEIPTVARACC"" type=""MXGLAccountQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""CHANGEBY"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""CHANGEDATE"" nillable=""true"" type=""MXDateTimeQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""DISABLED"" type=""MXBooleanQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""OLDCONTROLACC"" type=""MXGLAccountQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""OLDSHRINKAGEACC"" type=""MXGLAccountQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""OLDINVCOSTADJACC"" type=""MXGLAccountQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""CLASSSTRUCTUREID"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""GISPARAM1"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""GISPARAM2"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""GISPARAM3"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""SOURCESYSID"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""OWNERSYSID"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""EXTERNALREFID"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""SENDERSYSID"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""SITEID"" type=""MXStringQueryType"">
              <xs:annotation>
                <xs:documentation>Unique Key Component</xs:documentation>
              </xs:annotation>
            </xs:element>
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""ORGID"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""INTLABREC"" type=""MXGLAccountQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""ISDEFAULT"" type=""MXBooleanQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""SHIPTOADDRESSCODE"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""SHIPTOLABORCODE"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""BILLTOADDRESSCODE"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""BILLTOLABORCODE"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""STATUS"" type=""MXDomainQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""SERVICEADDRESSCODE"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""LOCATIONSID"" nillable=""true"" type=""MXLongQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""USEINPOPR"" type=""MXBooleanQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""TOOLCONTROLACC"" type=""MXGLAccountQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""LANGCODE"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""HASLD"" type=""MXBooleanQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""AUTOWOGEN"" type=""MXBooleanQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""STATUSDATE"" nillable=""true"" type=""MXDateTimeQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""INVOWNER"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""ISREPAIRFACILITY"" type=""MXBooleanQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""PLUSCDUEDATE"" nillable=""true"" type=""MXDateTimeQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""PLUSCLOOP"" type=""MXBooleanQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""PLUSCPMEXTDATE"" type=""MXBooleanQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFMBLDGCLASS1"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFMBLDGCLASS2"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFMPMJOB"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFMPORTFOLIO"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFMCONTNUM"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFMLOCLVL"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFMLOCPOS"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""CLIENTLOCREF"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""CONTRACTNO"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFMCLIENTACC"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFM_PMBPN"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFM_RWBPN"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFMSOURCESYS"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFMCLNAME"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFMCLPHONE"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""LOCOWNER"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""SUBOWNER"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""SUBOWNER2"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""LOCATTRIBUTE1"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""LOCATTRIBUTE2"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""LOCATTRIBUTE3"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""LOCATTRIBUTE4"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""LOCATTRIBUTE5"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""LOCATTRIBUTE6"" type=""MXStringQueryType"" />
            <xs:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFMSUPER"" type=""MXStringQueryType"" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attributeGroup ref=""QueryClausePropertyGroup"" />
  </xs:complexType>
  <xs:element name=""LOCATIONSMbo"" type=""LOCATIONSMboType"" />
  <xs:element name=""LOCATIONSMboSet"" type=""LOCATIONSMboSetType"" />
  <xs:element name=""LOCATIONSMboKey"" type=""LOCATIONSMboKeyType"" />
  <xs:element name=""LOCATIONSMboKeySet"" type=""LOCATIONSMboKeySetType"" />
  <xs:element name=""LOCATIONSMboQuery"" type=""LOCATIONSMboQueryType"" />
  <xs:complexType name=""CreateMXVISIONLOCQUERYType"">
    <xs:sequence>
      <xs:element ref=""MXVISIONLOCQUERYSet"" />
    </xs:sequence>
    <xs:attributeGroup ref=""CommonContentGroup"" />
  </xs:complexType>
  <xs:complexType name=""InvokeMXVISIONLOCQUERYType"">
    <xs:sequence>
      <xs:element ref=""MXVISIONLOCQUERYSet"" />
    </xs:sequence>
    <xs:attributeGroup ref=""CommonContentGroup"" />
  </xs:complexType>
  <xs:complexType name=""QueryMXVISIONLOCQUERYType"">
    <xs:sequence>
      <xs:element ref=""MXVISIONLOCQUERYQuery"" />
    </xs:sequence>
    <xs:attributeGroup ref=""CommonContentGroup"" />
    <xs:attributeGroup ref=""QueryContentGroup"" />
  </xs:complexType>
  <xs:complexType name=""SyncMXVISIONLOCQUERYType"">
    <xs:sequence>
      <xs:element ref=""MXVISIONLOCQUERYSet"" />
    </xs:sequence>
    <xs:attributeGroup ref=""CommonContentGroup"" />
  </xs:complexType>
  <xs:complexType name=""PublishMXVISIONLOCQUERYType"">
    <xs:sequence>
      <xs:element ref=""MXVISIONLOCQUERYSet"" />
    </xs:sequence>
    <xs:attributeGroup ref=""CommonContentGroup"" />
    <xs:attributeGroup ref=""PublishingContentGroup"" />
  </xs:complexType>
  <xs:complexType name=""UpdateMXVISIONLOCQUERYType"">
    <xs:sequence>
      <xs:element ref=""MXVISIONLOCQUERYSet"" />
    </xs:sequence>
    <xs:attributeGroup ref=""CommonContentGroup"" />
  </xs:complexType>
  <xs:complexType name=""DeleteMXVISIONLOCQUERYType"">
    <xs:sequence>
      <xs:element ref=""MXVISIONLOCQUERYSet"" />
    </xs:sequence>
    <xs:attributeGroup ref=""CommonContentGroup"" />
  </xs:complexType>
  <xs:complexType name=""InvokeMXVISIONLOCQUERYResponseType"">
    <xs:sequence>
      <xs:element ref=""MXVISIONLOCQUERYSet"" />
    </xs:sequence>
    <xs:attributeGroup ref=""CommonContentGroup"" />
  </xs:complexType>
  <xs:complexType name=""CreateMXVISIONLOCQUERYResponseType"">
    <xs:sequence>
      <xs:element minOccurs=""0"" ref=""LOCATIONSMboKeySet"" />
    </xs:sequence>
    <xs:attributeGroup ref=""CommonContentGroup"" />
  </xs:complexType>
  <xs:complexType name=""QueryMXVISIONLOCQUERYResponseType"">
    <xs:sequence>
      <xs:element ref=""MXVISIONLOCQUERYSet"" />
    </xs:sequence>
    <xs:attributeGroup ref=""CommonContentGroup"" />
    <xs:attributeGroup ref=""ResponseContentGroup"" />
  </xs:complexType>
  <xs:complexType name=""SyncMXVISIONLOCQUERYResponseType"">
    <xs:sequence />
    <xs:attributeGroup ref=""CommonContentGroup"" />
  </xs:complexType>
  <xs:complexType name=""DeleteMXVISIONLOCQUERYResponseType"">
    <xs:sequence />
    <xs:attributeGroup ref=""CommonContentGroup"" />
  </xs:complexType>
  <xs:complexType name=""UpdateMXVISIONLOCQUERYResponseType"">
    <xs:sequence />
    <xs:attributeGroup ref=""CommonContentGroup"" />
  </xs:complexType>
  <xs:element name=""UpdateMXVISIONLOCQUERY"" type=""UpdateMXVISIONLOCQUERYType"" />
  <xs:element name=""QueryMXVISIONLOCQUERY"" type=""QueryMXVISIONLOCQUERYType"" />
  <xs:element name=""CreateMXVISIONLOCQUERY"" type=""CreateMXVISIONLOCQUERYType"" />
  <xs:element name=""SyncMXVISIONLOCQUERY"" type=""SyncMXVISIONLOCQUERYType"" />
  <xs:element name=""DeleteMXVISIONLOCQUERY"" type=""DeleteMXVISIONLOCQUERYType"" />
  <xs:element name=""PublishMXVISIONLOCQUERY"" type=""PublishMXVISIONLOCQUERYType"" />
  <xs:element name=""InvokeMXVISIONLOCQUERY"" type=""InvokeMXVISIONLOCQUERYType"" />
  <xs:element name=""InvokeMXVISIONLOCQUERYResponse"" type=""InvokeMXVISIONLOCQUERYResponseType"" />
  <xs:element name=""QueryMXVISIONLOCQUERYResponse"" type=""QueryMXVISIONLOCQUERYResponseType"" />
  <xs:element name=""CreateMXVISIONLOCQUERYResponse"" type=""CreateMXVISIONLOCQUERYResponseType"" />
  <xs:element name=""SyncMXVISIONLOCQUERYResponse"" type=""SyncMXVISIONLOCQUERYResponseType"" />
  <xs:element name=""UpdateMXVISIONLOCQUERYResponse"" type=""UpdateMXVISIONLOCQUERYResponseType"" />
  <xs:element name=""DeleteMXVISIONLOCQUERYResponse"" type=""DeleteMXVISIONLOCQUERYResponseType"" />
</xs:schema>";
        
        public MTFMVISIONFM_MTFMVISIONLOCQUERY_www_ibm_com_maximo() {
        }
        
        public override string XmlContent {
            get {
                return _strSchema;
            }
        }
        
        public override string[] RootNodes {
            get {
                string[] _RootElements = new string [21];
                _RootElements[0] = "MXVISIONLOCQUERY";
                _RootElements[1] = "MXVISIONLOCQUERYSet";
                _RootElements[2] = "MXVISIONLOCQUERYQuery";
                _RootElements[3] = "LOCATIONSMbo";
                _RootElements[4] = "LOCATIONSMboSet";
                _RootElements[5] = "LOCATIONSMboKey";
                _RootElements[6] = "LOCATIONSMboKeySet";
                _RootElements[7] = "LOCATIONSMboQuery";
                _RootElements[8] = "UpdateMXVISIONLOCQUERY";
                _RootElements[9] = "QueryMXVISIONLOCQUERY";
                _RootElements[10] = "CreateMXVISIONLOCQUERY";
                _RootElements[11] = "SyncMXVISIONLOCQUERY";
                _RootElements[12] = "DeleteMXVISIONLOCQUERY";
                _RootElements[13] = "PublishMXVISIONLOCQUERY";
                _RootElements[14] = "InvokeMXVISIONLOCQUERY";
                _RootElements[15] = "InvokeMXVISIONLOCQUERYResponse";
                _RootElements[16] = "QueryMXVISIONLOCQUERYResponse";
                _RootElements[17] = "CreateMXVISIONLOCQUERYResponse";
                _RootElements[18] = "SyncMXVISIONLOCQUERYResponse";
                _RootElements[19] = "UpdateMXVISIONLOCQUERYResponse";
                _RootElements[20] = "DeleteMXVISIONLOCQUERYResponse";
                return _RootElements;
            }
        }
        
        protected override object RawSchema {
            get {
                return _rawSchema;
            }
            set {
                _rawSchema = value;
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"MXVISIONLOCQUERY")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"MXVISIONLOCQUERY"})]
        public sealed class MXVISIONLOCQUERY : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public MXVISIONLOCQUERY() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "MXVISIONLOCQUERY";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"MXVISIONLOCQUERYSet")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"MXVISIONLOCQUERYSet"})]
        public sealed class MXVISIONLOCQUERYSet : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public MXVISIONLOCQUERYSet() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "MXVISIONLOCQUERYSet";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"MXVISIONLOCQUERYQuery")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"MXVISIONLOCQUERYQuery"})]
        public sealed class MXVISIONLOCQUERYQuery : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public MXVISIONLOCQUERYQuery() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "MXVISIONLOCQUERYQuery";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"LOCATIONSMbo")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"LOCATIONSMbo"})]
        public sealed class LOCATIONSMbo : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public LOCATIONSMbo() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "LOCATIONSMbo";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"LOCATIONSMboSet")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"LOCATIONSMboSet"})]
        public sealed class LOCATIONSMboSet : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public LOCATIONSMboSet() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "LOCATIONSMboSet";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"LOCATIONSMboKey")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"LOCATIONSMboKey"})]
        public sealed class LOCATIONSMboKey : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public LOCATIONSMboKey() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "LOCATIONSMboKey";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"LOCATIONSMboKeySet")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"LOCATIONSMboKeySet"})]
        public sealed class LOCATIONSMboKeySet : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public LOCATIONSMboKeySet() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "LOCATIONSMboKeySet";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"LOCATIONSMboQuery")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"LOCATIONSMboQuery"})]
        public sealed class LOCATIONSMboQuery : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public LOCATIONSMboQuery() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "LOCATIONSMboQuery";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"UpdateMXVISIONLOCQUERY")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"UpdateMXVISIONLOCQUERY"})]
        public sealed class UpdateMXVISIONLOCQUERY : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public UpdateMXVISIONLOCQUERY() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "UpdateMXVISIONLOCQUERY";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"QueryMXVISIONLOCQUERY")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"QueryMXVISIONLOCQUERY"})]
        public sealed class QueryMXVISIONLOCQUERY : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public QueryMXVISIONLOCQUERY() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "QueryMXVISIONLOCQUERY";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"CreateMXVISIONLOCQUERY")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"CreateMXVISIONLOCQUERY"})]
        public sealed class CreateMXVISIONLOCQUERY : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public CreateMXVISIONLOCQUERY() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "CreateMXVISIONLOCQUERY";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"SyncMXVISIONLOCQUERY")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"SyncMXVISIONLOCQUERY"})]
        public sealed class SyncMXVISIONLOCQUERY : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public SyncMXVISIONLOCQUERY() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "SyncMXVISIONLOCQUERY";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"DeleteMXVISIONLOCQUERY")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"DeleteMXVISIONLOCQUERY"})]
        public sealed class DeleteMXVISIONLOCQUERY : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public DeleteMXVISIONLOCQUERY() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "DeleteMXVISIONLOCQUERY";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"PublishMXVISIONLOCQUERY")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"PublishMXVISIONLOCQUERY"})]
        public sealed class PublishMXVISIONLOCQUERY : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public PublishMXVISIONLOCQUERY() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "PublishMXVISIONLOCQUERY";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"InvokeMXVISIONLOCQUERY")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"InvokeMXVISIONLOCQUERY"})]
        public sealed class InvokeMXVISIONLOCQUERY : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public InvokeMXVISIONLOCQUERY() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "InvokeMXVISIONLOCQUERY";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"InvokeMXVISIONLOCQUERYResponse")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"InvokeMXVISIONLOCQUERYResponse"})]
        public sealed class InvokeMXVISIONLOCQUERYResponse : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public InvokeMXVISIONLOCQUERYResponse() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "InvokeMXVISIONLOCQUERYResponse";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"QueryMXVISIONLOCQUERYResponse")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"QueryMXVISIONLOCQUERYResponse"})]
        public sealed class QueryMXVISIONLOCQUERYResponse : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public QueryMXVISIONLOCQUERYResponse() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "QueryMXVISIONLOCQUERYResponse";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"CreateMXVISIONLOCQUERYResponse")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"CreateMXVISIONLOCQUERYResponse"})]
        public sealed class CreateMXVISIONLOCQUERYResponse : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public CreateMXVISIONLOCQUERYResponse() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "CreateMXVISIONLOCQUERYResponse";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"SyncMXVISIONLOCQUERYResponse")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"SyncMXVISIONLOCQUERYResponse"})]
        public sealed class SyncMXVISIONLOCQUERYResponse : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public SyncMXVISIONLOCQUERYResponse() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "SyncMXVISIONLOCQUERYResponse";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"UpdateMXVISIONLOCQUERYResponse")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"UpdateMXVISIONLOCQUERYResponse"})]
        public sealed class UpdateMXVISIONLOCQUERYResponse : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public UpdateMXVISIONLOCQUERYResponse() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "UpdateMXVISIONLOCQUERYResponse";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"DeleteMXVISIONLOCQUERYResponse")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"DeleteMXVISIONLOCQUERYResponse"})]
        public sealed class DeleteMXVISIONLOCQUERYResponse : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public DeleteMXVISIONLOCQUERYResponse() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "DeleteMXVISIONLOCQUERYResponse";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
    }
}
