namespace MFM.Lbg.Schemas {
    using Microsoft.XLANGs.BaseTypes;
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.BizTalk.Schema.Compiler", "3.0.1.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [SchemaType(SchemaTypeEnum.Document)]
    [Microsoft.XLANGs.BaseTypes.PropertyAttribute(typeof(global::MFM.Lbg.Schemas.WL_ROUTING), XPath = @"/*[local-name()='PublishMTFMWOLOGS' and namespace-uri()='http://www.ibm.com/maximo']/*[local-name()='MTFMWOLOGSSet' and namespace-uri()='http://www.ibm.com/maximo']/*[local-name()='WORKLOG' and namespace-uri()='http://www.ibm.com/maximo']/*[local-name()='WORKORDER' and namespace-uri()='http://www.ibm.com/maximo']/*[local-name()='WOLO2' and namespace-uri()='http://www.ibm.com/maximo']", XsdType = @"string")]
    [Microsoft.XLANGs.BaseTypes.PropertyAttribute(typeof(global::MFM.Lbg.Schemas.WL_SYSTEM), XPath = @"/*[local-name()='PublishMTFMWOLOGS' and namespace-uri()='http://www.ibm.com/maximo']/*[local-name()='MTFMWOLOGSSet' and namespace-uri()='http://www.ibm.com/maximo']/*[local-name()='WORKLOG' and namespace-uri()='http://www.ibm.com/maximo']/*[local-name()='WORKORDER' and namespace-uri()='http://www.ibm.com/maximo']/*[local-name()='SOURCESYSID' and namespace-uri()='http://www.ibm.com/maximo']", XsdType = @"string")]
    [System.SerializableAttribute()]
    [SchemaRoots(new string[] {@"WORKLOGMbo", @"WORKLOGMboSet", @"WORKLOGMboKey", @"WORKLOGMboKeySet", @"WORKLOGMboQuery", @"MTFMWOLOGS", @"MTFMWOLOGSSet", @"MTFMWOLOGSQuery", @"UpdateMTFMWOLOGS", @"QueryMTFMWOLOGS", @"CreateMTFMWOLOGS", @"SyncMTFMWOLOGS", @"DeleteMTFMWOLOGS", @"PublishMTFMWOLOGS", @"InvokeMTFMWOLOGS", @"InvokeMTFMWOLOGSResponse", @"QueryMTFMWOLOGSResponse", @"CreateMTFMWOLOGSResponse", @"SyncMTFMWOLOGSResponse", @"UpdateMTFMWOLOGSResponse", @"DeleteMTFMWOLOGSResponse"})]
    [Microsoft.XLANGs.BaseTypes.SchemaReference(@"MFM.Lbg.Schemas.PS_PublishMTFMWOLOGS", typeof(global::MFM.Lbg.Schemas.PS_PublishMTFMWOLOGS))]
    public sealed class MTFMWOLOGSService : Microsoft.XLANGs.BaseTypes.SchemaBase {
        
        [System.NonSerializedAttribute()]
        private static object _rawSchema;
        
        [System.NonSerializedAttribute()]
        private const string _strSchema = @"<?xml version=""1.0"" encoding=""utf-16""?>
<xsd:schema xmlns=""http://www.ibm.com/maximo"" xmlns:b=""http://schemas.microsoft.com/BizTalk/2003"" xmlns:ns0=""https://MFM.Lbg.Schemas.PS_PublishMTFMWOLOGS"" attributeFormDefault=""unqualified"" elementFormDefault=""qualified"" targetNamespace=""http://www.ibm.com/maximo"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <xsd:annotation>
    <xsd:appinfo>
      <b:imports>
        <b:namespace prefix=""ns0"" uri=""https://MFM.Lbg.Schemas.PS_PublishMTFMWOLOGS"" location=""MFM.Lbg.Schemas.PS_PublishMTFMWOLOGS"" />
      </b:imports>
    </xsd:appinfo>
  </xsd:annotation>
  <xsd:simpleType name=""ProcessingActionType"">
    <xsd:annotation>
      <xsd:documentation>Enumerated List of Processing Actions supported by Maximo Services</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base=""xsd:token"">
      <xsd:enumeration value=""Add"" />
      <xsd:enumeration value=""Change"" />
      <xsd:enumeration value=""Replace"" />
      <xsd:enumeration value=""Delete"" />
      <xsd:enumeration value=""AddChange"" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name=""OperandModeType"">
    <xsd:annotation>
      <xsd:documentation>Enumerated List of operand modes supported by Maximo Query</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base=""xsd:token"">
      <xsd:enumeration value=""OR"" />
      <xsd:enumeration value=""AND"" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name=""MboRelationshipType"">
    <xsd:restriction base=""xsd:string"" />
  </xsd:simpleType>
  <xsd:simpleType name=""EventType"">
    <xsd:annotation>
      <xsd:documentation>Boolean flag identifying if a published MOS was the result of an event. 1 implies event</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base=""xsd:boolean"">
      <xsd:pattern value=""0|1"" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name=""ChangeIndicatorType"">
    <xsd:annotation>
      <xsd:documentation>Boolean flag identifying if a field has a new value. Applicable only for a MOS generated by an event</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base=""xsd:boolean"">
      <xsd:pattern value=""1"" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name=""QueryOperatorType"">
    <xsd:annotation>
      <xsd:documentation>Operator identifying the QBE action to be performed on the field it is associated with</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base=""xsd:token"">
      <xsd:enumeration value=""="" />
      <xsd:enumeration value=""!="" />
      <xsd:enumeration value=""&lt;"" />
      <xsd:enumeration value=""&lt;="" />
      <xsd:enumeration value=""&gt;"" />
      <xsd:enumeration value=""&gt;="" />
      <xsd:enumeration value=""EW"" />
      <xsd:enumeration value=""SW"" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name=""BooleanType"">
    <xsd:restriction base=""xsd:boolean"">
      <xsd:pattern value=""0|1"" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name=""MaximoVersionType"">
    <xsd:annotation>
      <xsd:documentation>This is a concatenated string that identifies the major version, minor version, build and dbbuild</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base=""xsd:string"" />
  </xsd:simpleType>
  <xsd:complexType name=""MXStringType"">
    <xsd:simpleContent>
      <xsd:extension base=""xsd:string"">
        <xsd:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  <xsd:complexType name=""MXLangStringType"">
    <xsd:simpleContent>
      <xsd:extension base=""xsd:string"">
        <xsd:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
        <xsd:attribute fixed=""1"" name=""languageEnabled"" type=""xsd:boolean"" use=""optional"" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  <xsd:complexType name=""MXDoubleType"">
    <xsd:simpleContent>
      <xsd:extension base=""xsd:double"">
        <xsd:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  <xsd:complexType name=""MXFloatType"">
    <xsd:simpleContent>
      <xsd:extension base=""xsd:float"">
        <xsd:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  <xsd:complexType name=""MXLongType"">
    <xsd:simpleContent>
      <xsd:extension base=""xsd:long"">
        <xsd:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  <xsd:complexType name=""MXIntType"">
    <xsd:simpleContent>
      <xsd:extension base=""xsd:int"">
        <xsd:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  <xsd:complexType name=""MXBooleanType"">
    <xsd:simpleContent>
      <xsd:extension base=""BooleanType"">
        <xsd:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  <xsd:complexType name=""MXDateTimeType"">
    <xsd:simpleContent>
      <xsd:extension base=""xsd:dateTime"">
        <xsd:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  <xsd:complexType name=""MXBinaryType"">
    <xsd:simpleContent>
      <xsd:extension base=""xsd:base64Binary"">
        <xsd:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  <xsd:complexType name=""MXCryptoType"">
    <xsd:simpleContent>
      <xsd:extension base=""xsd:base64Binary"">
        <xsd:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
        <xsd:attribute default=""1"" name=""mxencrypted"" type=""BooleanType"" use=""optional"" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  <xsd:complexType name=""MXGLComponentType"">
    <xsd:simpleContent>
      <xsd:extension base=""xsd:string"">
        <xsd:attribute name=""glorder"" use=""required"">
          <xsd:simpleType>
            <xsd:restriction base=""xsd:int"">
              <xsd:minInclusive value=""0"" />
              <xsd:maxExclusive value=""20"" />
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:attribute>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  <xsd:complexType name=""MXGLAccountType"">
    <xsd:sequence>
      <xsd:element minOccurs=""0"" name=""VALUE"" type=""xsd:string"" />
      <xsd:element minOccurs=""0"" maxOccurs=""20"" name=""GLCOMP"" type=""MXGLComponentType"" />
    </xsd:sequence>
    <xsd:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
  </xsd:complexType>
  <xsd:complexType name=""MXDomainType"">
    <xsd:simpleContent>
      <xsd:extension base=""xsd:string"">
        <xsd:attribute name=""maxvalue"" type=""xsd:string"" use=""optional"" />
        <xsd:attribute name=""changed"" type=""ChangeIndicatorType"" use=""optional"" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  <xsd:complexType name=""MXStringQueryType"">
    <xsd:simpleContent>
      <xsd:extension base=""xsd:string"">
        <xsd:attribute name=""operator"" type=""QueryOperatorType"" use=""optional"" />
        <xsd:attribute name=""operandModeOR"" type=""xsd:boolean"" use=""optional"" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  <xsd:complexType name=""MXDoubleQueryType"">
    <xsd:simpleContent>
      <xsd:extension base=""xsd:double"">
        <xsd:attribute name=""operator"" type=""QueryOperatorType"" use=""optional"" />
        <xsd:attribute name=""operandModeOR"" type=""xsd:boolean"" use=""optional"" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  <xsd:complexType name=""MXFloatQueryType"">
    <xsd:simpleContent>
      <xsd:extension base=""xsd:float"">
        <xsd:attribute name=""operator"" type=""QueryOperatorType"" use=""optional"" />
        <xsd:attribute name=""operandModeOR"" type=""xsd:boolean"" use=""optional"" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  <xsd:complexType name=""MXLongQueryType"">
    <xsd:simpleContent>
      <xsd:extension base=""xsd:string"">
        <xsd:attribute name=""operator"" type=""QueryOperatorType"" use=""optional"" />
        <xsd:attribute name=""operandModeOR"" type=""xsd:boolean"" use=""optional"" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  <xsd:complexType name=""MXIntQueryType"">
    <xsd:simpleContent>
      <xsd:extension base=""xsd:int"">
        <xsd:attribute name=""operator"" type=""QueryOperatorType"" use=""optional"" />
        <xsd:attribute name=""operandModeOR"" type=""xsd:boolean"" use=""optional"" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  <xsd:complexType name=""MXBooleanQueryType"">
    <xsd:simpleContent>
      <xsd:extension base=""BooleanType"">
        <xsd:attribute name=""operator"" type=""QueryOperatorType"" use=""optional"" />
        <xsd:attribute name=""operandModeOR"" type=""xsd:boolean"" use=""optional"" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  <xsd:complexType name=""MXDateTimeQueryType"">
    <xsd:simpleContent>
      <xsd:extension base=""xsd:dateTime"">
        <xsd:attribute name=""operator"" type=""QueryOperatorType"" use=""optional"" />
        <xsd:attribute name=""operandModeOR"" type=""xsd:boolean"" use=""optional"" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  <xsd:complexType name=""MXGLComponentQueryType"">
    <xsd:simpleContent>
      <xsd:extension base=""xsd:string"">
        <xsd:attribute name=""glorder"" use=""required"">
          <xsd:simpleType>
            <xsd:restriction base=""xsd:int"">
              <xsd:minInclusive value=""0"" />
              <xsd:maxExclusive value=""20"" />
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:attribute>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  <xsd:complexType name=""MXGLAccountQueryType"">
    <xsd:sequence>
      <xsd:element minOccurs=""0"" name=""VALUE"" type=""xsd:string"" />
    </xsd:sequence>
    <xsd:attribute name=""operator"" type=""QueryOperatorType"" use=""optional"" />
    <xsd:attribute name=""operandModeOR"" type=""xsd:boolean"" use=""optional"" />
  </xsd:complexType>
  <xsd:complexType name=""MXDomainQueryType"">
    <xsd:simpleContent>
      <xsd:extension base=""xsd:string"">
        <xsd:attribute name=""maxvalue"" type=""xsd:string"" use=""optional"" />
        <xsd:attribute name=""operator"" type=""QueryOperatorType"" use=""optional"" />
        <xsd:attribute name=""operandModeOR"" type=""xsd:boolean"" use=""optional"" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  <xsd:attributeGroup name=""ObjectStructurePropertyGroup"">
    <xsd:attribute name=""action"" type=""ProcessingActionType"" use=""optional"" />
    <xsd:attribute name=""relationship"" type=""xsd:string"" use=""optional"" />
    <xsd:attribute name=""deleteForInsert"" type=""xsd:string"" use=""optional"" />
  </xsd:attributeGroup>
  <xsd:attributeGroup name=""CommonContentGroup"">
    <xsd:attribute name=""creationDateTime"" type=""xsd:dateTime"" use=""optional"" />
    <xsd:attribute name=""baseLanguage"" type=""xsd:string"" use=""optional"" />
    <xsd:attribute name=""transLanguage"" type=""xsd:string"" use=""optional"" />
    <xsd:attribute name=""messageID"" type=""xsd:string"" use=""optional"" />
    <xsd:attribute name=""maximoVersion"" type=""MaximoVersionType"" use=""optional"" />
  </xsd:attributeGroup>
  <xsd:attributeGroup name=""PublishingContentGroup"">
    <xsd:attribute default=""0"" name=""event"" type=""EventType"" use=""optional"" />
  </xsd:attributeGroup>
  <xsd:attributeGroup name=""QueryContentGroup"">
    <xsd:attribute default=""0"" name=""uniqueResult"" type=""BooleanType"" use=""optional"" />
    <xsd:attribute name=""maxItems"" type=""xsd:positiveInteger"" use=""optional"" />
    <xsd:attribute default=""0"" name=""rsStart"" type=""xsd:integer"" use=""optional"" />
  </xsd:attributeGroup>
  <xsd:attributeGroup name=""QueryClausePropertyGroup"">
    <xsd:attribute name=""orderby"" type=""xsd:string"" use=""optional"" />
    <xsd:attribute default=""AND"" name=""operandMode"" type=""OperandModeType"" use=""optional"" />
  </xsd:attributeGroup>
  <xsd:attributeGroup name=""ResponseContentGroup"">
    <xsd:attribute name=""rsStart"" type=""xsd:integer"" use=""optional"" />
    <xsd:attribute name=""rsCount"" type=""xsd:integer"" use=""optional"" />
    <xsd:attribute name=""rsTotal"" type=""xsd:integer"" use=""optional"" />
  </xsd:attributeGroup>
  <xsd:complexType name=""WORKLOGKeyType"">
    <xsd:sequence>
      <xsd:element name=""WORKLOGID"" nillable=""true"" type=""MXLongType"">
        <xsd:annotation>
          <xsd:documentation>Unique Key Component</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name=""WORKLOGObjectType"">
    <xsd:sequence>
      <xsd:element minOccurs=""0"" name=""WORKLOGID"" nillable=""true"" type=""MXLongType"">
        <xsd:annotation>
          <xsd:documentation>Unique Key Component</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element minOccurs=""0"" name=""LOGTYPE"" type=""MXDomainType"" />
      <xsd:element minOccurs=""0"" name=""CREATEBY"" type=""MXStringType"" />
      <xsd:element minOccurs=""0"" name=""CREATEDATE"" nillable=""true"" type=""MXDateTimeType"" />
      <xsd:element minOccurs=""0"" name=""CLIENTVIEWABLE"" type=""MXBooleanType"" />
      <xsd:element minOccurs=""0"" name=""DESCRIPTION"" type=""MXStringType"" />
      <xsd:element minOccurs=""0"" name=""SITEID"" type=""MXStringType"" />
      <xsd:element minOccurs=""0"" name=""ORGID"" type=""MXStringType"" />
      <xsd:element minOccurs=""0"" name=""MODIFYBY"" type=""MXStringType"" />
      <xsd:element minOccurs=""0"" name=""MODIFYDATE"" nillable=""true"" type=""MXDateTimeType"" />
      <xsd:element minOccurs=""0"" name=""RECORDKEY"" type=""MXStringType"" />
      <xsd:element minOccurs=""0"" name=""CLASS"" type=""MXStringType"" />
      <xsd:element minOccurs=""0"" name=""LANGCODE"" type=""MXStringType"" />
      <xsd:element minOccurs=""0"" name=""HASLD"" type=""MXBooleanType"" />
      <xsd:element minOccurs=""0"" name=""M2SMS_PWD"" type=""MXStringType"" />
      <xsd:element minOccurs=""0"" name=""EMAIL_ADDRESS"" type=""MXStringType"" />
      <xsd:element minOccurs=""0"" name=""MTFMJM8ID"" nillable=""true"" type=""MXLongType"" />
    </xsd:sequence>
    <xsd:attribute name=""action"" type=""ProcessingActionType"" use=""optional"" />
  </xsd:complexType>
  <xsd:complexType name=""WORKLOGMboKeyType"">
    <xsd:sequence>
      <xsd:element minOccurs=""0"" name=""WORKLOG"" type=""WORKLOGKeyType"" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name=""WORKLOGMboKeySetType"">
    <xsd:sequence>
      <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""WORKLOG"" type=""WORKLOGKeyType"" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name=""WORKLOGMboSetType"">
    <xsd:sequence>
      <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""WORKLOG"" type=""WORKLOGObjectType"" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name=""WORKLOGMboType"">
    <xsd:sequence>
      <xsd:element minOccurs=""0"" name=""WORKLOG"" type=""WORKLOGObjectType"" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name=""WORKLOGMboQueryType"">
    <xsd:sequence>
      <xsd:element minOccurs=""0"" name=""WHERE"" type=""xsd:string"" />
      <xsd:element minOccurs=""0"" name=""WORKLOG"">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""WORKLOGID"" nillable=""true"" type=""MXLongQueryType"">
              <xsd:annotation>
                <xsd:documentation>Unique Key Component</xsd:documentation>
              </xsd:annotation>
            </xsd:element>
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""LOGTYPE"" type=""MXDomainQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""CREATEBY"" type=""MXStringQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""CREATEDATE"" nillable=""true"" type=""MXDateTimeQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""CLIENTVIEWABLE"" type=""MXBooleanQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""DESCRIPTION"" type=""MXStringQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""SITEID"" type=""MXStringQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""ORGID"" type=""MXStringQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MODIFYBY"" type=""MXStringQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MODIFYDATE"" nillable=""true"" type=""MXDateTimeQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""RECORDKEY"" type=""MXStringQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""CLASS"" type=""MXStringQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""LANGCODE"" type=""MXStringQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""HASLD"" type=""MXBooleanQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""M2SMS_PWD"" type=""MXStringQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""EMAIL_ADDRESS"" type=""MXStringQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFMJM8ID"" nillable=""true"" type=""MXLongQueryType"" />
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
    <xsd:attributeGroup ref=""QueryClausePropertyGroup"" />
  </xsd:complexType>
  <xsd:element name=""WORKLOGMbo"" type=""WORKLOGMboType"" />
  <xsd:element name=""WORKLOGMboSet"" type=""WORKLOGMboSetType"" />
  <xsd:element name=""WORKLOGMboKey"" type=""WORKLOGMboKeyType"" />
  <xsd:element name=""WORKLOGMboKeySet"" type=""WORKLOGMboKeySetType"" />
  <xsd:element name=""WORKLOGMboQuery"" type=""WORKLOGMboQueryType"" />
  <xsd:complexType name=""MTFMWOLOGS_WORKLOGType"">
    <xsd:sequence>
      <xsd:element minOccurs=""0"" name=""MAXINTERRORMSG"" type=""xsd:string"" />
      <xsd:element minOccurs=""0"" name=""CLASS"" type=""MXStringType"" />
      <xsd:element minOccurs=""0"" name=""CLIENTVIEWABLE"" type=""MXBooleanType"" />
      <xsd:element minOccurs=""0"" name=""CREATEBY"" type=""MXStringType"" />
      <xsd:element minOccurs=""0"" name=""CREATEDATE"" nillable=""true"" type=""MXDateTimeType"" />
      <xsd:element minOccurs=""0"" name=""DESCRIPTION"" type=""MXStringType"" />
      <xsd:element minOccurs=""0"" name=""DESCRIPTION_LONGDESCRIPTION"" type=""MXStringType"" />
      <xsd:element minOccurs=""0"" name=""EMAIL_ADDRESS"" type=""MXStringType"" />
      <xsd:element minOccurs=""0"" name=""HASLD"" type=""MXBooleanType"" />
      <xsd:element minOccurs=""0"" name=""LANGCODE"" type=""MXStringType"" />
      <xsd:element minOccurs=""0"" name=""LOGTYPE"" type=""MXDomainType"" />
      <xsd:element minOccurs=""0"" name=""M2SMS_PWD"" type=""MXStringType"" />
      <xsd:element minOccurs=""0"" name=""MODIFYBY"" type=""MXStringType"" />
      <xsd:element minOccurs=""0"" name=""MODIFYDATE"" nillable=""true"" type=""MXDateTimeType"" />
      <xsd:element minOccurs=""0"" name=""MTFMJM8ID"" nillable=""true"" type=""MXLongType"" />
      <xsd:element minOccurs=""0"" name=""ORGID"" type=""MXStringType"" />
      <xsd:element minOccurs=""0"" name=""RECORDKEY"" type=""MXStringType"" />
      <xsd:element minOccurs=""0"" name=""SITEID"" type=""MXStringType"" />
      <xsd:element minOccurs=""0"" name=""WORKLOGID"" nillable=""true"" type=""MXLongType"">
        <xsd:annotation>
          <xsd:documentation>Unique Key Component</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element minOccurs=""0"" maxOccurs=""1"" name=""WORKORDER"" type=""MTFMWOLOGS_WORKORDERType"" />
    </xsd:sequence>
    <xsd:attributeGroup ref=""ObjectStructurePropertyGroup"" />
    <xsd:attribute name=""transLanguage"" type=""xsd:string"" use=""optional"" />
  </xsd:complexType>
  <xsd:complexType name=""MTFMWOLOGS_WORKORDERType"">
    <xsd:sequence>
      <xsd:element minOccurs=""0"" name=""MTFMCLIENTREF"" type=""MXStringType"" />
      <xsd:element minOccurs=""0"" name=""MTFMSENDTOVIS"" type=""MXBooleanType"" />
      <xsd:element minOccurs=""0"" name=""ORGID"" type=""MXStringType"" />
      <xsd:element minOccurs=""0"" name=""SITEID"" type=""MXStringType"">
        <xsd:annotation>
          <xsd:documentation>Unique Key Component</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element minOccurs=""0"" name=""SOURCESYSID"" type=""MXStringType"" />
      <xsd:element minOccurs=""0"" name=""STATUS"" type=""MXDomainType"" />
      <xsd:element minOccurs=""0"" maxOccurs=""1"" name=""WOLO2"" type=""MXStringType"" />
      <xsd:element minOccurs=""0"" name=""WOLO3"" type=""MXStringType"" />
      <xsd:element minOccurs=""0"" name=""WONUM"" type=""MXStringType"">
        <xsd:annotation>
          <xsd:documentation>Unique Key Component</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>
    <xsd:attributeGroup ref=""ObjectStructurePropertyGroup"" />
  </xsd:complexType>
  <xsd:complexType name=""MTFMWOLOGSType"">
    <xsd:sequence>
      <xsd:element minOccurs=""0"" name=""WORKLOG"" type=""MTFMWOLOGS_WORKLOGType"" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name=""MTFMWOLOGSSetType"">
    <xsd:sequence>
      <xsd:element minOccurs=""0"" maxOccurs=""1"" name=""WORKLOG"" type=""MTFMWOLOGS_WORKLOGType"" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name=""MTFMWOLOGSQueryType"">
    <xsd:sequence>
      <xsd:element minOccurs=""0"" name=""WHERE"" type=""xsd:string"" />
      <xsd:element minOccurs=""0"" name=""WORKLOG"">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""CLASS"" type=""MXStringQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""CLIENTVIEWABLE"" type=""MXBooleanQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""CREATEBY"" type=""MXStringQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""CREATEDATE"" nillable=""true"" type=""MXDateTimeQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""DESCRIPTION"" type=""MXStringQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""EMAIL_ADDRESS"" type=""MXStringQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""HASLD"" type=""MXBooleanQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""LANGCODE"" type=""MXStringQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""LOGTYPE"" type=""MXDomainQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""M2SMS_PWD"" type=""MXStringQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MODIFYBY"" type=""MXStringQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MODIFYDATE"" nillable=""true"" type=""MXDateTimeQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFMJM8ID"" nillable=""true"" type=""MXLongQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""ORGID"" type=""MXStringQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""RECORDKEY"" type=""MXStringQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""SITEID"" type=""MXStringQueryType"" />
            <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""WORKLOGID"" nillable=""true"" type=""MXLongQueryType"">
              <xsd:annotation>
                <xsd:documentation>Unique Key Component</xsd:documentation>
              </xsd:annotation>
            </xsd:element>
            <xsd:element minOccurs=""0"" name=""WORKORDER"">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFMCLIENTREF"" type=""MXStringQueryType"" />
                  <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""MTFMSENDTOVIS"" type=""MXBooleanQueryType"" />
                  <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""ORGID"" type=""MXStringQueryType"" />
                  <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""SITEID"" type=""MXStringQueryType"">
                    <xsd:annotation>
                      <xsd:documentation>Unique Key Component</xsd:documentation>
                    </xsd:annotation>
                  </xsd:element>
                  <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""SOURCESYSID"" type=""MXStringQueryType"" />
                  <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""STATUS"" type=""MXDomainQueryType"" />
                  <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""WOLO2"" type=""MXStringQueryType"" />
                  <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""WOLO3"" type=""MXStringQueryType"" />
                  <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""WONUM"" type=""MXStringQueryType"">
                    <xsd:annotation>
                      <xsd:documentation>Unique Key Component</xsd:documentation>
                    </xsd:annotation>
                  </xsd:element>
                </xsd:sequence>
                <xsd:attribute name=""filter"" type=""xsd:boolean"" use=""optional"" />
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
    <xsd:attributeGroup ref=""QueryClausePropertyGroup"" />
  </xsd:complexType>
  <xsd:complexType name=""MTFMWOLOGSCombinedKeySetType"">
    <xsd:sequence>
      <xsd:element minOccurs=""0"" maxOccurs=""unbounded"" name=""WORKLOG"">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name=""WORKLOGID"" nillable=""true"" type=""MXLongType"">
              <xsd:annotation>
                <xsd:documentation>Unique Key Component</xsd:documentation>
              </xsd:annotation>
            </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name=""MTFMWOLOGS"" type=""MTFMWOLOGSType"" />
  <xsd:element name=""MTFMWOLOGSSet"" type=""MTFMWOLOGSSetType"" />
  <xsd:element name=""MTFMWOLOGSQuery"" type=""MTFMWOLOGSQueryType"" />
  <xsd:complexType name=""CreateMTFMWOLOGSType"">
    <xsd:sequence>
      <xsd:element ref=""MTFMWOLOGSSet"" />
    </xsd:sequence>
    <xsd:attributeGroup ref=""CommonContentGroup"" />
  </xsd:complexType>
  <xsd:complexType name=""InvokeMTFMWOLOGSType"">
    <xsd:sequence>
      <xsd:element ref=""MTFMWOLOGSSet"" />
    </xsd:sequence>
    <xsd:attributeGroup ref=""CommonContentGroup"" />
  </xsd:complexType>
  <xsd:complexType name=""QueryMTFMWOLOGSType"">
    <xsd:sequence>
      <xsd:element ref=""MTFMWOLOGSQuery"" />
    </xsd:sequence>
    <xsd:attributeGroup ref=""CommonContentGroup"" />
    <xsd:attributeGroup ref=""QueryContentGroup"" />
  </xsd:complexType>
  <xsd:complexType name=""SyncMTFMWOLOGSType"">
    <xsd:sequence>
      <xsd:element ref=""MTFMWOLOGSSet"" />
    </xsd:sequence>
    <xsd:attributeGroup ref=""CommonContentGroup"" />
  </xsd:complexType>
  <xsd:complexType name=""PublishMTFMWOLOGSType"">
    <xsd:sequence>
      <xsd:element ref=""MTFMWOLOGSSet"" />
    </xsd:sequence>
    <xsd:attributeGroup ref=""CommonContentGroup"" />
    <xsd:attributeGroup ref=""PublishingContentGroup"" />
  </xsd:complexType>
  <xsd:complexType name=""UpdateMTFMWOLOGSType"">
    <xsd:sequence>
      <xsd:element ref=""MTFMWOLOGSSet"" />
    </xsd:sequence>
    <xsd:attributeGroup ref=""CommonContentGroup"" />
  </xsd:complexType>
  <xsd:complexType name=""DeleteMTFMWOLOGSType"">
    <xsd:sequence>
      <xsd:element ref=""MTFMWOLOGSSet"" />
    </xsd:sequence>
    <xsd:attributeGroup ref=""CommonContentGroup"" />
  </xsd:complexType>
  <xsd:complexType name=""InvokeMTFMWOLOGSResponseType"">
    <xsd:sequence>
      <xsd:element ref=""MTFMWOLOGSSet"" />
    </xsd:sequence>
    <xsd:attributeGroup ref=""CommonContentGroup"" />
  </xsd:complexType>
  <xsd:complexType name=""CreateMTFMWOLOGSResponseType"">
    <xsd:sequence>
      <xsd:element minOccurs=""0"" ref=""WORKLOGMboKeySet"" />
    </xsd:sequence>
    <xsd:attributeGroup ref=""CommonContentGroup"" />
  </xsd:complexType>
  <xsd:complexType name=""QueryMTFMWOLOGSResponseType"">
    <xsd:sequence>
      <xsd:element ref=""MTFMWOLOGSSet"" />
    </xsd:sequence>
    <xsd:attributeGroup ref=""CommonContentGroup"" />
    <xsd:attributeGroup ref=""ResponseContentGroup"" />
  </xsd:complexType>
  <xsd:complexType name=""SyncMTFMWOLOGSResponseType"">
    <xsd:sequence />
    <xsd:attributeGroup ref=""CommonContentGroup"" />
  </xsd:complexType>
  <xsd:complexType name=""DeleteMTFMWOLOGSResponseType"">
    <xsd:sequence />
    <xsd:attributeGroup ref=""CommonContentGroup"" />
  </xsd:complexType>
  <xsd:complexType name=""UpdateMTFMWOLOGSResponseType"">
    <xsd:sequence />
    <xsd:attributeGroup ref=""CommonContentGroup"" />
  </xsd:complexType>
  <xsd:element name=""UpdateMTFMWOLOGS"" type=""UpdateMTFMWOLOGSType"" />
  <xsd:element name=""QueryMTFMWOLOGS"" type=""QueryMTFMWOLOGSType"" />
  <xsd:element name=""CreateMTFMWOLOGS"" type=""CreateMTFMWOLOGSType"" />
  <xsd:element name=""SyncMTFMWOLOGS"" type=""SyncMTFMWOLOGSType"" />
  <xsd:element name=""DeleteMTFMWOLOGS"" type=""DeleteMTFMWOLOGSType"" />
  <xsd:element name=""PublishMTFMWOLOGS"" type=""PublishMTFMWOLOGSType"">
    <xsd:annotation>
      <xsd:appinfo>
        <b:properties>
          <b:property name=""ns0:WL_ROUTING"" xpath=""/*[local-name()='PublishMTFMWOLOGS' and namespace-uri()='http://www.ibm.com/maximo']/*[local-name()='MTFMWOLOGSSet' and namespace-uri()='http://www.ibm.com/maximo']/*[local-name()='WORKLOG' and namespace-uri()='http://www.ibm.com/maximo']/*[local-name()='WORKORDER' and namespace-uri()='http://www.ibm.com/maximo']/*[local-name()='WOLO2' and namespace-uri()='http://www.ibm.com/maximo']"" />
          <b:property name=""ns0:WL_SYSTEM"" xpath=""/*[local-name()='PublishMTFMWOLOGS' and namespace-uri()='http://www.ibm.com/maximo']/*[local-name()='MTFMWOLOGSSet' and namespace-uri()='http://www.ibm.com/maximo']/*[local-name()='WORKLOG' and namespace-uri()='http://www.ibm.com/maximo']/*[local-name()='WORKORDER' and namespace-uri()='http://www.ibm.com/maximo']/*[local-name()='SOURCESYSID' and namespace-uri()='http://www.ibm.com/maximo']"" />
        </b:properties>
      </xsd:appinfo>
    </xsd:annotation>
  </xsd:element>
  <xsd:element name=""InvokeMTFMWOLOGS"" type=""InvokeMTFMWOLOGSType"" />
  <xsd:element name=""InvokeMTFMWOLOGSResponse"" type=""InvokeMTFMWOLOGSResponseType"" />
  <xsd:element name=""QueryMTFMWOLOGSResponse"" type=""QueryMTFMWOLOGSResponseType"" />
  <xsd:element name=""CreateMTFMWOLOGSResponse"" type=""CreateMTFMWOLOGSResponseType"" />
  <xsd:element name=""SyncMTFMWOLOGSResponse"" type=""SyncMTFMWOLOGSResponseType"" />
  <xsd:element name=""UpdateMTFMWOLOGSResponse"" type=""UpdateMTFMWOLOGSResponseType"" />
  <xsd:element name=""DeleteMTFMWOLOGSResponse"" type=""DeleteMTFMWOLOGSResponseType"" />
</xsd:schema>";
        
        public MTFMWOLOGSService() {
        }
        
        public override string XmlContent {
            get {
                return _strSchema;
            }
        }
        
        public override string[] RootNodes {
            get {
                string[] _RootElements = new string [21];
                _RootElements[0] = "WORKLOGMbo";
                _RootElements[1] = "WORKLOGMboSet";
                _RootElements[2] = "WORKLOGMboKey";
                _RootElements[3] = "WORKLOGMboKeySet";
                _RootElements[4] = "WORKLOGMboQuery";
                _RootElements[5] = "MTFMWOLOGS";
                _RootElements[6] = "MTFMWOLOGSSet";
                _RootElements[7] = "MTFMWOLOGSQuery";
                _RootElements[8] = "UpdateMTFMWOLOGS";
                _RootElements[9] = "QueryMTFMWOLOGS";
                _RootElements[10] = "CreateMTFMWOLOGS";
                _RootElements[11] = "SyncMTFMWOLOGS";
                _RootElements[12] = "DeleteMTFMWOLOGS";
                _RootElements[13] = "PublishMTFMWOLOGS";
                _RootElements[14] = "InvokeMTFMWOLOGS";
                _RootElements[15] = "InvokeMTFMWOLOGSResponse";
                _RootElements[16] = "QueryMTFMWOLOGSResponse";
                _RootElements[17] = "CreateMTFMWOLOGSResponse";
                _RootElements[18] = "SyncMTFMWOLOGSResponse";
                _RootElements[19] = "UpdateMTFMWOLOGSResponse";
                _RootElements[20] = "DeleteMTFMWOLOGSResponse";
                return _RootElements;
            }
        }
        
        protected override object RawSchema {
            get {
                return _rawSchema;
            }
            set {
                _rawSchema = value;
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"WORKLOGMbo")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"WORKLOGMbo"})]
        public sealed class WORKLOGMbo : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public WORKLOGMbo() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "WORKLOGMbo";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"WORKLOGMboSet")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"WORKLOGMboSet"})]
        public sealed class WORKLOGMboSet : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public WORKLOGMboSet() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "WORKLOGMboSet";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"WORKLOGMboKey")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"WORKLOGMboKey"})]
        public sealed class WORKLOGMboKey : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public WORKLOGMboKey() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "WORKLOGMboKey";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"WORKLOGMboKeySet")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"WORKLOGMboKeySet"})]
        public sealed class WORKLOGMboKeySet : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public WORKLOGMboKeySet() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "WORKLOGMboKeySet";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"WORKLOGMboQuery")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"WORKLOGMboQuery"})]
        public sealed class WORKLOGMboQuery : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public WORKLOGMboQuery() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "WORKLOGMboQuery";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"MTFMWOLOGS")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"MTFMWOLOGS"})]
        public sealed class MTFMWOLOGS : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public MTFMWOLOGS() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "MTFMWOLOGS";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"MTFMWOLOGSSet")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"MTFMWOLOGSSet"})]
        public sealed class MTFMWOLOGSSet : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public MTFMWOLOGSSet() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "MTFMWOLOGSSet";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"MTFMWOLOGSQuery")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"MTFMWOLOGSQuery"})]
        public sealed class MTFMWOLOGSQuery : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public MTFMWOLOGSQuery() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "MTFMWOLOGSQuery";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"UpdateMTFMWOLOGS")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"UpdateMTFMWOLOGS"})]
        public sealed class UpdateMTFMWOLOGS : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public UpdateMTFMWOLOGS() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "UpdateMTFMWOLOGS";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"QueryMTFMWOLOGS")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"QueryMTFMWOLOGS"})]
        public sealed class QueryMTFMWOLOGS : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public QueryMTFMWOLOGS() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "QueryMTFMWOLOGS";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"CreateMTFMWOLOGS")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"CreateMTFMWOLOGS"})]
        public sealed class CreateMTFMWOLOGS : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public CreateMTFMWOLOGS() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "CreateMTFMWOLOGS";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"SyncMTFMWOLOGS")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"SyncMTFMWOLOGS"})]
        public sealed class SyncMTFMWOLOGS : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public SyncMTFMWOLOGS() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "SyncMTFMWOLOGS";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"DeleteMTFMWOLOGS")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"DeleteMTFMWOLOGS"})]
        public sealed class DeleteMTFMWOLOGS : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public DeleteMTFMWOLOGS() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "DeleteMTFMWOLOGS";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"PublishMTFMWOLOGS")]
        [Microsoft.XLANGs.BaseTypes.PropertyAttribute(typeof(global::MFM.Lbg.Schemas.WL_ROUTING), XPath = @"/*[local-name()='PublishMTFMWOLOGS' and namespace-uri()='http://www.ibm.com/maximo']/*[local-name()='MTFMWOLOGSSet' and namespace-uri()='http://www.ibm.com/maximo']/*[local-name()='WORKLOG' and namespace-uri()='http://www.ibm.com/maximo']/*[local-name()='WORKORDER' and namespace-uri()='http://www.ibm.com/maximo']/*[local-name()='WOLO2' and namespace-uri()='http://www.ibm.com/maximo']", XsdType = @"string")]
        [Microsoft.XLANGs.BaseTypes.PropertyAttribute(typeof(global::MFM.Lbg.Schemas.WL_SYSTEM), XPath = @"/*[local-name()='PublishMTFMWOLOGS' and namespace-uri()='http://www.ibm.com/maximo']/*[local-name()='MTFMWOLOGSSet' and namespace-uri()='http://www.ibm.com/maximo']/*[local-name()='WORKLOG' and namespace-uri()='http://www.ibm.com/maximo']/*[local-name()='WORKORDER' and namespace-uri()='http://www.ibm.com/maximo']/*[local-name()='SOURCESYSID' and namespace-uri()='http://www.ibm.com/maximo']", XsdType = @"string")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"PublishMTFMWOLOGS"})]
        public sealed class PublishMTFMWOLOGS : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public PublishMTFMWOLOGS() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "PublishMTFMWOLOGS";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"InvokeMTFMWOLOGS")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"InvokeMTFMWOLOGS"})]
        public sealed class InvokeMTFMWOLOGS : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public InvokeMTFMWOLOGS() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "InvokeMTFMWOLOGS";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"InvokeMTFMWOLOGSResponse")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"InvokeMTFMWOLOGSResponse"})]
        public sealed class InvokeMTFMWOLOGSResponse : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public InvokeMTFMWOLOGSResponse() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "InvokeMTFMWOLOGSResponse";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"QueryMTFMWOLOGSResponse")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"QueryMTFMWOLOGSResponse"})]
        public sealed class QueryMTFMWOLOGSResponse : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public QueryMTFMWOLOGSResponse() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "QueryMTFMWOLOGSResponse";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"CreateMTFMWOLOGSResponse")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"CreateMTFMWOLOGSResponse"})]
        public sealed class CreateMTFMWOLOGSResponse : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public CreateMTFMWOLOGSResponse() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "CreateMTFMWOLOGSResponse";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"SyncMTFMWOLOGSResponse")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"SyncMTFMWOLOGSResponse"})]
        public sealed class SyncMTFMWOLOGSResponse : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public SyncMTFMWOLOGSResponse() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "SyncMTFMWOLOGSResponse";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"UpdateMTFMWOLOGSResponse")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"UpdateMTFMWOLOGSResponse"})]
        public sealed class UpdateMTFMWOLOGSResponse : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public UpdateMTFMWOLOGSResponse() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "UpdateMTFMWOLOGSResponse";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
        
        [Schema(@"http://www.ibm.com/maximo",@"DeleteMTFMWOLOGSResponse")]
        [System.SerializableAttribute()]
        [SchemaRoots(new string[] {@"DeleteMTFMWOLOGSResponse"})]
        public sealed class DeleteMTFMWOLOGSResponse : Microsoft.XLANGs.BaseTypes.SchemaBase {
            
            [System.NonSerializedAttribute()]
            private static object _rawSchema;
            
            public DeleteMTFMWOLOGSResponse() {
            }
            
            public override string XmlContent {
                get {
                    return _strSchema;
                }
            }
            
            public override string[] RootNodes {
                get {
                    string[] _RootElements = new string [1];
                    _RootElements[0] = "DeleteMTFMWOLOGSResponse";
                    return _RootElements;
                }
            }
            
            protected override object RawSchema {
                get {
                    return _rawSchema;
                }
                set {
                    _rawSchema = value;
                }
            }
        }
    }
}
